<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: portal/modules/FAQ/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'SSS' ,
   'LBL_MODULE_TITLE' => 'SSS: Ana Sayfa' ,
   'LBL_BACK_TO_TOP' => 'Başa Geri Dön' ,
   'LBL_SUCCESSFUL_QUERY' => 'Başarılı' ,
   'LBL_ERROR_QUERY' => 'Hata' ,
   'ERR_FAQ_LIST_RETRIEVE' => 'Hata: SSS içeriği şu anda getirilemiyor.' ,
   'ERR_FAQ_LIST_RETRIEVE_RETRY' => 'SOAP çağrısı tekrarlanmakta...' ,
   'LBL_FAQ_EMPTY' => 'Bilgi Veritabanında SSS olarak belirlenmiş yazı bulunmamaktadır.' );

?>
