<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Help/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Müşteriler' ,
   'LBL_MODULE_TITLE' => 'Müşteriler: Ana Sayfa' ,
   'LBL_SEARCH_FORM_TITLE' => 'Müşteri Arama' ,
   'LBL_LIST_FORM_TITLE' => 'Müşteri Listesi' ,
   'LBL_NEW_FORM_TITLE' => 'Müşteri Oluştur' ,
   'LNK_NEW_CONTACT' => 'Kontak Oluştur' ,
   'LNK_NEW_ACCOUNT' => 'Müşteri Oluştur' ,
   'LNK_NEW_OPPORTUNITY' => 'Fırsat Oluştur' ,
   'LNK_NEW_CASE' => 'Talep Oluştur' ,
   'LNK_NEW_NOTE' => 'Not veya Ek Oluştur' ,
   'LNK_NEW_CALL' => 'Tel. Araması Planla' ,
   'LNK_NEW_EMAIL' => 'E-Posta Arşivle' ,
   'LNK_NEW_MEETING' => 'Toplantı Planla' ,
   'LNK_NEW_TASK' => 'Görev Oluştur' ,
   'ERR_DELETE_RECORD' => 'Müşteriyi silmek için bir kayıt numarası belirtilmelidir.' );

?>
