<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/DocumentRevisions/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Doküman Revizyonu' ,
   'LNK_NEW_DOCUMENT' => 'Doküman Oluştur' ,
   'LNK_DOCUMENT_LIST' => 'Doküman Listesi' ,
   'LBL_REVISION_NAME' => 'Revizyon No' ,
   'LBL_FILENAME' => 'Dosya adı:' ,
   'LBL_MIME' => 'Mime Tipi' ,
   'LBL_REVISION' => 'Revizyon' ,
   'LBL_DOCUMENT' => 'İlişkili Doküman' ,
   'LBL_LATEST_REVISION' => 'En Son Revizyon' ,
   'LBL_CHANGE_LOG' => 'Değişiklik Tarihçesi' ,
   'LBL_ACTIVE_DATE' => 'Yayın Tarihi' ,
   'LBL_EXPIRATION_DATE' => 'Son Geçerlilik Tarihi' ,
   'LBL_FILE_EXTENSION' => 'Dosya uzantısı' ,
   'LBL_DET_CREATED_BY' => 'Oluşturan:' ,
   'LBL_DET_DATE_CREATED' => 'Oluşturulma Tarihi:' ,
   'LBL_DOC_NAME' => 'Doküman İsmi:' ,
   'LBL_DOC_VERSION' => 'Revizyon:' ,
   'LBL_REV_LIST_REVISION' => 'Revizyon' ,
   'LBL_REV_LIST_ENTERED' => 'Oluşturulma Tarihi' ,
   'LBL_REV_LIST_CREATED' => 'Oluşturan' ,
   'LBL_REV_LIST_LOG' => 'Değişiklik Tarihçesi' ,
   'LBL_REV_LIST_FILENAME' => 'Dosya adı' ,
   'LBL_CURRENT_DOC_VERSION' => 'En Son Revizyon:' ,
   'LBL_SEARCH_FORM_TITLE' => 'Doküman Arama' ,
   'ERR_FILENAME' => 'Dosya İsmi' ,
   'ERR_DOC_VERSION' => 'Doküman Sürümü' ,
   'ERR_DELETE_CONFIRM' => 'Bu revizyonu silmek istediğinizden emin misiniz?' ,
   'ERR_DELETE_LATEST_VERSION' => 'Dokümanın son revize edilmiş halini silmeye izniniz yok.' ,
   'LNK_NEW_MAIL_MERGE' => 'Posta Birleştir' ,
   'LBL_DOC_ID' => 'Doküman Kaynak ID' ,
   'LBL_DOC_TYPE' => 'Kaynak' ,
   'LBL_DOC_URL' => 'Belge Kaynağı URL' );

?>
