<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/SugarFeed/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_TEAM' => 'Takım' ,
   'LBL_TEAM_ID' => 'Takım ID' ,
   'LBL_ASSIGNED_TO_ID' => 'Atanan Kullanıcı ID' ,
   'LBL_ASSIGNED_TO_NAME' => 'Atanan Kişi' ,
   'LBL_ID' => 'ID' ,
   'LBL_DATE_ENTERED' => 'Oluşturulma Tarihi' ,
   'LBL_DATE_MODIFIED' => 'Değiştirilme Tarihi' ,
   'LBL_MODIFIED' => 'Değiştiren' ,
   'LBL_MODIFIED_ID' => 'Değiştiren ID' ,
   'LBL_MODIFIED_NAME' => 'Değiştiren Kişinin İsmi' ,
   'LBL_CREATED' => 'Oluşturan' ,
   'LBL_CREATED_ID' => 'Oluşturan ID' ,
   'LBL_DESCRIPTION' => 'Tanım' ,
   'LBL_DELETED' => 'Silindi' ,
   'LBL_NAME' => 'İsim' ,
   'LBL_SAVING' => 'Kaydediyor...' ,
   'LBL_SAVED' => 'Kaydedildi' ,
   'LBL_CREATED_USER' => 'Oluşturan Kullanıcı' ,
   'LBL_MODIFIED_USER' => 'Değiştiren Kullanıcı' ,
   'LBL_LIST_FORM_TITLE' => 'Sugar Bilgi Besleme Listesi' ,
   'LBL_MODULE_NAME' => 'Sugar Bilgi Beslemesi' ,
   'LBL_MODULE_TITLE' => 'Sugar Bilgi Beslemesi' ,
   'LBL_DASHLET_DISABLED' => 'Uyarı: Sugar Bilgi Besleme sistemi pasif hale getirildi, tekrar aktif edilene kadar yeni bir bilgi kaydı yollanmayacak' ,
   'LBL_ADMIN_SETTINGS' => 'Sugar Bilgi Besleme Ayarları' ,
   'LBL_RECORDS_DELETED' => 'Daha önceki bütün Sugar Bilgi Besleme kayıtları silindi. Eğer Sugar Bilgi Besleme sistemi aktive edilirse, yeni kayıtlar otomatik olarak oluşturulacak.' ,
   'LBL_CONFIRM_DELETE_RECORDS' => 'Bütün Sugar Bilgi Besleme kayıtlarını silmek istediğinizden emin misiniz?' ,
   'LBL_FLUSH_RECORDS' => 'Bilgi Besleme Kayıtlarını Sil' ,
   'LBL_ENABLE_FEED' => 'Sugar Bilgi Besleme Dashlet&#39;ini Etkinleştir' ,
   'LBL_ENABLE_MODULE_LIST' => 'Bilgi Beslemelerinin Aktive Edileceği Modüller' ,
   'LBL_HOMEPAGE_TITLE' => 'Sugar Bilgi Beslemesi' ,
   'LNK_NEW_RECORD' => 'Sugar Bilgi Beslemesi Oluştur' ,
   'LNK_LIST' => 'Beslemeler' ,
   'LBL_SEARCH_FORM_TITLE' => 'Sugar Bilgi Beslemesini Ara' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => 'Tarihçeyi Gör' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Aktiviteler' ,
   'LBL_SUGAR_FEED_SUBPANEL_TITLE' => 'Beslemeler' ,
   'LBL_NEW_FORM_TITLE' => 'Yeni Sugar Bilgi Beslemesi' ,
   'LBL_ALL' => 'Tümü' ,
   'LBL_USER_FEED' => 'Kullanıcı Bilgi Beslemesi' ,
   'LBL_ENABLE_USER_FEED' => 'Kullanıcı Bilgi Beslemesini Aktifleştir' ,
   'LBL_TO' => 'Takıma Gönderilecek' ,
   'LBL_IS' => 'eşit' ,
   'LBL_DONE' => 'Tamam' ,
   'LBL_TITLE' => 'Başlık' ,
   'LBL_ROWS' => 'Satırlar' ,
   'LBL_MY_FAVORITES_ONLY' => 'Sadece Favorilerim' ,
   'LBL_ENABLE_EXTERNAL_CONNECTORS' => '<i>Not: Kullanıcıların Facebook ve Twitter mesajlarını görebilmesi için, Facebook ve Twitter bağlayıcılarını içeren Bağlayıcılar sayfasına gidin.</i>' ,
   'LBL_CATEGORIES' => 'Modüller' ,
   'LBL_TIME_LAST_WEEK' => 'Geçen Hafta' ,
   'LBL_TIME_WEEKS' => 'Hafta' ,
   'LBL_TIME_DAYS' => 'Gün' ,
   'LBL_TIME_YESTERDAY' => 'Dün' ,
   'LBL_TIME_HOURS' => 'Saat' ,
   'LBL_TIME_HOUR' => 'Saat' ,
   'LBL_TIME_MINUTES' => 'Dakika' ,
   'LBL_TIME_MINUTE' => 'Dakika' ,
   'LBL_TIME_SECONDS' => 'Saniye' ,
   'LBL_TIME_SECOND' => 'Saniye' ,
   'LBL_TIME_AGO' => 'önce' ,
   'CREATED_CONTACT' => '<b>YENİ</b> bir kontak oluşturuldu' ,
   'CREATED_OPPORTUNITY' => '<b>YENİ</b> bir kontak oluşturuldu' ,
   'CREATED_CASE' => '<b>YENİ</b> bir kontak oluşturuldu' ,
   'CREATED_LEAD' => '<b>YENİ</b> bir kontak oluşturuldu' ,
   'FOR' => 'için' ,
   'CLOSED_CASE' => 'bir talep <b>KAPATILDI</b>' ,
   'CONVERTED_LEAD' => 'bir potansiyel <b>DÖNÜŞTÜRÜLDÜ</b>' ,
   'WON_OPPORTUNITY' => 'bir fırsat <b>KAZANILDI</b>' ,
   'WITH' => 'ile birlikte' ,
   'LBL_LINK_TYPE_Link' => 'Bağlantı' ,
   'LBL_LINK_TYPE_Image' => 'Resim' ,
   'LBL_LINK_TYPE_YouTube' => 'YouTube&#153;' ,
   'LBL_SELECT' => 'Seç' ,
   'LBL_POST' => 'Gönder' ,
   'LBL_EXTERNAL_PREFIX' => 'Harici: ' ,
   'LBL_EXTERNAL_WARNING' => '"Harici" olarak etiketli öğeler için bir <a href="?module=EAPM">harici hesap</a> gerekir.' ,
   'LBL_AUTHENTICATE' => 'Bağlan' ,
   'LBL_AUTHENTICATION_PENDING' => 'Seçmiş olduğunuz harici hesapların kimlik doğrulaması yapılmamış.  Seçenekler penceresine dönmek ve Harici hesaplar kimliğini doğrulamak için &#39;İptal&#39;  ya da kimlik doğrulaması olmadan devam etmek için &#39;Tamam&#39; düğmesine tıklayın.' ,
   'LBL_ADVANCED_SEARCH' => 'Gelişmiş Arama' ,
   'LBL_BASICSEARCH' => 'Temel Arama' ,
   'LBL_SHOW_MORE_OPTIONS' => 'Daha Fazla Seçenek Göster' ,
   'LBL_HIDE_OPTIONS' => 'Seçenekleri Gizle' ,
   'LBL_VIEW' => 'Göster' ,
   'LBL_POST_TITLE' => 'Güncel Durum Gönderimi: ' ,
   'LBL_URL_LINK_TITLE' => 'Kullanılacak URL Bağlantısı' ,
   'LBL_TEAM_VISIBILITY_TITLE' => 'Bu iletiyi görebilen takım' );

?>
