<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ForecastSchedule/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Tahminler' ,
   'LNK_NEW_OPPORTUNITY' => 'Fırsat Oluştur' ,
   'LBL_MODULE_TITLE' => 'Tahminler' ,
   'LBL_LIST_FORM_TITLE' => 'Onaylanan Tahminler' ,
   'LNK_UPD_FORECAST' => 'Tahmin Çalışma Sayfası' ,
   'LNK_QUOTA' => 'Kotalar' ,
   'LNK_FORECAST_LIST' => 'Tahmin Tarihçesini Görüntüle' ,
   'LBL_FORECAST_HISTORY' => 'Tahminler: Tarihçe' ,
   'LBL_FORECAST_HISTORY_TITLE' => 'Tahminler: Tarihçe' ,
   'LBL_TIMEPERIOD_NAME' => 'Zaman Aralığı' ,
   'LBL_USER_NAME' => 'Kullanıcı İsmi' ,
   'LBL_REPORTS_TO_USER_NAME' => 'Rapor Edilen Kişi:' ,
   'LBL_FORECAST_ID' => 'ID' ,
   'LBL_FORECAST_TIME_ID' => 'Zaman Aralığı ID' ,
   'LBL_FORECAST_TYPE' => 'Tahmin Tipi' ,
   'LBL_FORECAST_OPP_COUNT' => 'Fırsatlar' ,
   'LBL_FORECAST_OPP_WEIGH' => 'Ağırlıklı Miktar' ,
   'LBL_FORECAST_OPP_COMMIT' => 'Olası Talep' ,
   'LBL_FORECAST_OPP_BEST_CASE' => 'En İyi Talep' ,
   'LBL_FORECAST_OPP_WORST' => 'En Kötü Talep' ,
   'LBL_FORECAST_USER' => 'Kullanıcı' ,
   'LBL_DATE_COMMITTED' => 'Onaylanan Tarih' ,
   'LBL_DATE_ENTERED' => 'Giriş Tarihi' ,
   'LBL_DATE_MODIFIED' => 'Değiştirilme Tarihi' ,
   'LBL_CREATED_BY' => 'Oluşturan' ,
   'LBL_DELETED' => 'Silindi' ,
   'LBL_QC_TIME_PERIOD' => 'Zaman Aralığı:' ,
   'LBL_QC_OPPORTUNITY_COUNT' => 'Fırsat Sayısı:' ,
   'LBL_QC_WEIGHT_VALUE' => 'Ağırlıklı Miktar:' ,
   'LBL_QC_COMMIT_VALUE' => 'Onaylanan Miktar:' ,
   'LBL_QC_COMMIT_BUTTON' => 'Onay' ,
   'LBL_QC_WORKSHEET_BUTTON' => 'Çalışma Sayfası' ,
   'LBL_QC_ROLL_COMMIT_VALUE' => 'Toplanmış Onaylanan Miktar:' ,
   'LBL_QC_DIRECT_FORECAST' => 'Doğrudan Tahminim:' ,
   'LBL_QC_ROLLUP_FORECAST' => 'Grubumun Tahmini:' ,
   'LBL_QC_UPCOMING_FORECASTS' => 'Tahminlerim' ,
   'LBL_QC_LAST_DATE_COMMITTED' => 'Son Onay Zamanı:' ,
   'LBL_QC_LAST_COMMIT_VALUE' => 'Son Onay Miktarı:' ,
   'LBL_QC_HEADER_DELIM' => 'Kime' ,
   'LBL_OW_OPPORTUNITIES' => 'Fırsat' ,
   'LBL_OW_ACCOUNTNAME' => 'Müşteri' ,
   'LBL_OW_REVENUE' => 'Tutar' ,
   'LBL_OW_WEIGHTED' => 'Ağırlıklı Miktar' ,
   'LBL_OW_MODULE_TITLE' => 'Fırsat Çalışma Sayfası' ,
   'LBL_OW_PROBABILITY' => 'Olasılık' ,
   'LBL_OW_NEXT_STEP' => 'Bir Sonraki Adım:' ,
   'LBL_OW_DESCRIPTION' => 'Tanım' ,
   'LBL_OW_TYPE' => 'Tipi' ,
   'LNK_NEW_TIMEPERIOD' => 'Zaman Aralığı Oluştur' ,
   'LNK_TIMEPERIOD_LIST' => 'Zaman Aralığını Gör' ,
   'LBL_SVFS_FORECASTDATE' => 'Planlama Başlangıç Tarihi' ,
   'LBL_SVFS_STATUS' => 'Durum' ,
   'LBL_SVFS_USER' => 'Kim İçin' ,
   'LBL_SVFS_CASCADE' => 'Raporlara basamaklandırılsın mı?' ,
   'LBL_SVFS_HEADER' => 'Tahmin Planlama:' ,
   'LB_FS_KEY' => 'ID' ,
   'LBL_FS_TIMEPERIOD_ID' => 'Zaman Aralığı ID' ,
   'LBL_FS_USER_ID' => 'Kullanıcı ID' ,
   'LBL_FS_TIMEPERIOD' => 'Zaman Aralığı' ,
   'LBL_FS_START_DATE' => 'Başlangıç Tarihi' ,
   'LBL_FS_END_DATE' => 'Bitiş Tarihi' ,
   'LBL_FS_FORECAST_START_DATE' => 'Tahmin Başlangıç Tarihi' ,
   'LBL_FS_STATUS' => 'Durum' ,
   'LBL_FS_FORECAST_FOR' => 'Planlanacak Kişi:' ,
   'LBL_FS_CASCADE' => 'Basamaklandır?' ,
   'LBL_FS_MODULE_NAME' => 'Tahmin Planlaması' ,
   'LBL_FS_CREATED_BY' => 'Oluşturan' ,
   'LBL_FS_DATE_ENTERED' => 'Giriş Tarihi' ,
   'LBL_FS_DATE_MODIFIED' => 'Değiştirilme Tarihi' ,
   'LBL_FS_DELETED' => 'Silindi' ,
   'LBL_FDR_USER_NAME' => 'Doğrudan Rapor' ,
   'LBL_FDR_OPPORTUNITIES' => 'Tahmindeki olasılıklar:' ,
   'LBL_FDR_WEIGH' => 'Fırsatların ağırlıklı miktarı:' ,
   'LBL_FDR_COMMIT' => 'Onaylanmış Miktar' ,
   'LBL_FDR_DATE_COMMIT' => 'Onay Tarihi' ,
   'LBL_DV_HEADER' => 'Tahminler: Çalışma Sayfası' ,
   'LBL_DV_MY_FORECASTS' => 'Tahminlerim' ,
   'LBL_DV_MY_TEAM' => 'Takımımın Tahminleri' ,
   'LBL_DV_TIMEPERIODS' => 'Zaman Aralıkları:' ,
   'LBL_DV_FORECAST_PERIOD' => 'Zaman Aralığı Tahmini' ,
   'LBL_DV_FORECAST_OPPORTUNITY' => 'Tahmin Fırsatları' ,
   'LBL_SEARCH' => 'Seç' ,
   'LBL_SEARCH_LABEL' => 'Seç' ,
   'LBL_COMMIT_HEADER' => 'Tahmin Onayla' ,
   'LBL_DV_LAST_COMMIT_DATE' => 'Son Onay Zamanı:' ,
   'LBL_DV_LAST_COMMIT_AMOUNT' => 'Son Onay Miktarları:' ,
   'LBL_DV_FORECAST_ROLLUP' => 'Tahmin Rollup' ,
   'LBL_DV_TIMEPERIOD' => 'Zaman Aralığı:' ,
   'LBL_DV_TIMPERIOD_DATES' => 'Tarih Alanı:' ,
   'LBL_LV_TIMPERIOD' => 'Zaman aralığı' ,
   'LBL_LV_TIMPERIOD_START_DATE' => 'Başlangıç Tarihi' ,
   'LBL_LV_TIMPERIOD_END_DATE' => 'Bitiş Tarihi' ,
   'LBL_LV_TYPE' => 'Tahmin Tipi' ,
   'LBL_LV_COMMIT_DATE' => 'Onaylanan Tarih' ,
   'LBL_LV_OPPORTUNITIES' => 'Fırsatlar' ,
   'LBL_LV_WEIGH' => 'Ağırlıklı Miktar' ,
   'LBL_LV_COMMIT' => 'Onaylanmış Miktar' ,
   'LBL_COMMIT_NOTE' => 'Seçili Zaman Periyodu için onaylanacak miktarları girin:' ,
   'LBL_COMMIT_MESSAGE' => 'Bu tutarı onaylamak ister misiniz?' ,
   'ERR_FORECAST_AMOUNT' => 'Onaylanan Miktar gereklidir ve sayı olmalıdır.' ,
   'LBL_FC_START_DATE' => 'Başlangıç Tarihi' ,
   'LBL_FC_USER' => 'Planlanacak Kişi' ,
   'LBL_NO_ACTIVE_TIMEPERIOD' => 'Tahminleme için Etkin zaman periyodu yok.' ,
   'LBL_FDR_ADJ_AMOUNT' => 'Ayarlanmış Miktar' ,
   'LBL_SAVE_WOKSHEET' => 'Çalışma Sayfasını Kaydet' ,
   'LBL_RESET_WOKSHEET' => 'Çalışma Sayfasını Sıfırla' ,
   'LBL_RESET_CHECK' => 'Seçilen zaman periyodu ve giriş yapmış kullanıcının tüm çalışma sayfası verileri silinecektir. Devam etmek ister misiniz?' ,
   'LB_FS_LIKELY_CASE' => 'Olası Talep' ,
   'LB_FS_WORST_CASE' => 'En Kötü Talep' ,
   'LB_FS_BEST_CASE' => 'En İyi Talep' ,
   'LBL_FDR_WK_LIKELY_CASE' => 'Tahmini Olası Talep' ,
   'LBL_FDR_WK_BEST_CASE' => 'Tahmini En İyi Talep' ,
   'LBL_FDR_WK_WORST_CASE' => 'Tahmini En Kötü Talep' ,
   'LBL_BEST_CASE' => 'En İyi Talep:' ,
   'LBL_LIKELY_CASE' => 'Olası Talep:' ,
   'LBL_WORST_CASE' => 'En Kötü Talep:' ,
   'LBL_FDR_C_BEST_CASE' => 'En İyi Talep' ,
   'LBL_FDR_C_WORST_CASE' => 'En Kötü Talep' ,
   'LBL_FDR_C_LIKELY_CASE' => 'Olası Talep' ,
   'LBL_QC_LAST_BEST_CASE' => 'En Son Onaylanan Miktar (En İyi Talep):' ,
   'LBL_QC_LAST_LIKELY_CASE' => 'En Son Onaylanan Miktar (Olası Talep):' ,
   'LBL_QC_LAST_WORST_CASE' => 'En Son Onaylanan Miktar (En Kötü Talep):' ,
   'LBL_QC_ROLL_BEST_VALUE' => 'Toplam Onaylanan Miktar (En İyi Talep):' ,
   'LBL_QC_ROLL_LIKELY_VALUE' => 'Toplam Onaylanan Miktar (Olası Talep):' ,
   'LBL_QC_ROLL_WORST_VALUE' => 'Toplam Onaylanan Miktar (En Kötü Talep):' ,
   'LBL_QC_COMMIT_BEST_CASE' => 'Onaylanan Miktar (En İyi Talep):' ,
   'LBL_QC_COMMIT_LIKELY_CASE' => 'Onaylanan Miktar (Olası Talep):' ,
   'LBL_QC_COMMIT_WORST_CASE' => 'Onaylanan Miktar (En Kötü Talep):' ,
   'LBL_EDIT_LAYOUT' => 'Yerleşimi Değiştir' );

?>
