<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/TaxRates/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Vergi Oranları' ,
   'LBL_MODULE_TITLE' => 'Vergi Oranı: Ana Sayfa' ,
   'LBL_SEARCH_FORM_TITLE' => 'Vergi Oranı Arama' ,
   'LBL_LIST_FORM_TITLE' => 'Vergi Oranı Listesi' ,
   'LBL_NEW_FORM_TITLE' => 'Yeni Vergi Oranı' ,
   'LBL_TAXRATE' => 'Vergi Oranı:' ,
   'LBL_LIST_NAME' => 'Vergi Oranı İsmi' ,
   'LBL_NAME' => 'Vergi Oranı İsmi:' ,
   'LBL_LIST_LIST_ORDER' => 'Sıra' ,
   'LBL_LIST_ORDER' => 'Sıra:' ,
   'LBL_LIST_STATUS' => 'Durum' ,
   'LBL_STATUS' => 'Durum:' ,
   'LBL_LIST_VALUE' => 'Yüzde' ,
   'LBL_VALUE' => 'Yüzde (%):' ,
   'LNK_NEW_SHIPPER' => 'Nakliyat Firma Listesi' ,
   'LNK_NEW_TAXRATE' => 'Vergi Oranı Listesi' ,
   'LNK_IMPORT_TAXRATES' => 'Vergi Oranı Verilerini Yükle' ,
   'NTC_DELETE_CONFIRMATION' => 'Bu kaydı silmek istediğinizden emin misiniz?' ,
   'ERR_DELETE_RECORD' => 'Vergi oranını silmek için bir kayıt no&#39;su girmelisiniz.' ,
   'NTC_STATUS' => 'Bu vergi oranının durumunu, İnaktif olarak belirleyerek Vergi Oranı açılır-listesinden kaldırın' ,
   'NTC_LIST_ORDER' => 'Bu vergi oranının, Vergi Oranı açılır-listesinde görünmesini istediğiniz sırayı belirleyin' ,
   'LBL_EDITLAYOUT' => 'Yerleşimi Değiştir' ,
   'LBL_CREATED_ID' => 'Oluşturan ID' ,
   'LBL_MODIFIED_ID' => 'Değiştiren ID' ,
   'LBL_EXPORT_MODIFIED_USER_ID' => 'Değiştirilmiş Kullanıcı ID&#39;si' ,
   'LBL_EXPORT_CREATED_BY' => 'Oluşturan ID' ,
   'taxrate_status_dom' => array (
      'Active' => 'Aktif' ,
      'Inactive' => 'İnaktif'   ));

?>
