<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/WorkFlowAlertShells/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Uyarılar' ,
   'LBL_MODULE_TITLE' => 'Uyarılar: Ana Sayfa' ,
   'LBL_MODULE_SECTION_TITLE' => 'Belirtilen koşullar sağlandığında' ,
   'LBL_SEARCH_FORM_TITLE' => 'İş Akış Uyarı Araması' ,
   'LBL_LIST_FORM_TITLE' => 'Uyarı Listesi' ,
   'LBL_NEW_FORM_TITLE' => 'İş Akış Uyarısı Oluştur' ,
   'LBL_LIST_NAME' => 'İsim' ,
   'LBL_LIST_ALERT_TYPE' => 'Uyarı Tipi' ,
   'LBL_LIST_ALERT_TEXT' => 'Uyarı Msj' ,
   'LBL_CUSTOM_TEMPLATE_NAME' => 'Özel Şablon' ,
   'LBL_NAME' => 'İsim:' ,
   'LBL_ALERT_TEXT' => 'Uyarı Yazısı:' ,
   'LBL_ALERT_TYPE' => 'Uyarı Tipi:' ,
   'LBL_SOURCE_TYPE' => 'Kaynak Tipi:' ,
   'LBL_LIST_TYPE' => 'Tipi:' ,
   'LBL_LIST_DETAILS' => 'Detaylar' ,
   'LNK_NEW_WORKFLOW' => 'İş Akış Tanımı Oluştur' ,
   'LNK_WORKFLOW' => 'İş Akış Tanımlarını Listele' ,
   'LBL_PARENT_WORKFLOW' => 'Ana İş Akış Konusu:' ,
   'LBL_RETURN_TO_WORKFLOW' => 'İş Akışı Tanımına Dön' ,
   'NTC_REMOVE_ALERT' => 'Bu uyarı ile onun tüm alıcılarını silmek istediğinizden emin misiniz?' ,
   'LBL_LIST_STATEMENT' => 'Olay Tanımı:' ,
   'STATEMENT_PART1' => 'Gönder' ,
   'STATEMENT_PART2' => 'kullanılan' ,
   'LNK_LIST_REPORTMAKER' => 'Rapor Listesi' ,
   'LNK_NEW_REPORTMAKER' => 'Yeni Rapor Oluştur' ,
   'LNK_LIST_DATASET' => 'Veri Kümesi Listesi' ,
   'LNK_NEW_DATASET' => 'Veri Kümesi Oluştur' ,
   'LNK_NEW_QUERYBUILDER' => 'Sorgu Oluştur' ,
   'LNK_QUERYBUILDER' => 'Sorgu Oluşturucusu' ,
   'LBL_ALL_REPORTS' => 'Bütün Raporlar' ,
   'NTC_DELETE_CONFIRMATION' => 'Bu kaydı silmek istediğinizden emin misiniz?' ,
   'ERR_DELETE_RECORD' => 'Ürünü silmek için bir kayıt numarası belirtmelisiniz.' ,
   'LBL_NEW_BUTTON_LABEL_ALERT' => 'Uyarı Oluştur' ,
   'LBL_NEW_BUTTON_KEY_ALERT' => 'A' ,
   'LBL_NEW_BUTTON_TITLE_ALERT' => 'Uyarı Oluştur' ,
   'LBL_NEW_BUTTON_LABEL_ACTION' => 'Aksiyon Oluştur' ,
   'LBL_NEW_BUTTON_KEY_ACTION' => 'C' ,
   'LBL_NEW_BUTTON_TITLE_ACTION' => 'Aksiyon Oluştur' ,
   'LBL_MODULE_NAME_COMBO' => 'Uyarılar' ,
   'LNK_ALERT_TEMPLATES' => 'Şablonları Uyar' ,
   'LNK_PROCESS_VIEW' => 'İş Akış Çalıştırma Sırası' ,
   'LBL_LIST_COMPONENTS' => 'Öğeler' ,
   'LBL_RECIPIENTS' => 'Alıcılar' ,
   'LBL_MODULE_TITLE_INVITE' => 'Kişi Davet Et' ,
   'LBL_SHOW' => 'Göster' ,
   'LBL_RECIPIENT_ERROR' => 'Bu alıcı hata içermektedir ve kullanılamaz.' ,
   'LBL_ALERT_ERRORS' => 'Uyarı: Aşağıda bulunan bir veya daha fazla uyarı hata içermektedir.' );

?>
