<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/WorkFlowActionShells/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Aksiyonlar' ,
   'LBL_MODULE_TITLE' => 'İş Akışı Tetikleyicileri: Ana Sayfa' ,
   'LBL_SEARCH_FORM_TITLE' => 'İş Akışı Tetikleyicisi Arama' ,
   'LBL_LIST_FORM_TITLE' => 'Aksiyon Listesi' ,
   'LBL_NEW_FORM_TITLE' => 'Tetikleyici Oluştur' ,
   'LBL_LIST_NAME' => 'Tetikleyici İsmi:' ,
   'LBL_LIST_TYPE' => 'Tipi:' ,
   'LBL_LIST_EVAL' => 'Deneme:' ,
   'LBL_LIST_FIELD' => 'Alan:' ,
   'LBL_NAME' => 'Tetikleyici İsmi:' ,
   'LBL_FIELD' => 'Alan:' ,
   'LBL_TYPE' => 'Tipi:' ,
   'LBL_EVAL' => 'Tetikleyici Değerlendirmesi:' ,
   'LBL_SHOW_PAST' => 'Eski Değeri Değiştir:' ,
   'LNK_NEW_TRIGGER' => 'Tetikleyici Oluştur' ,
   'LNK_TRIGGER' => 'İş Akışı Tetikleyicileri' ,
   'NTC_REMOVE_ACTION' => 'Bu aksiyonu silmek istediğinizden emin misiniz?' ,
   'LBL_ACTION_UPDATE_TITLE' => 'Hedef modüldeki alanları güncelle' ,
   'LBL_ACTION_UPDATE_REL_TITLE' => 'İlişkili modüldeki alanları güncelle' ,
   'LBL_ACTION_NEW_TITLE' => 'Hedef modül ile ilişkili bir modülde kayıt oluştur' ,
   'LBL_LIST_STATEMENT' => 'Olay Tanımı:' ,
   'LBL_ACTION_UPDATE' => 'Hedefteki alanı(ları) güncelle' ,
   'LBL_ACTION_UPDATE_REL' => 'Güncellenen ilişkili alanlar' ,
   'LBL_ACTION_UPDATE_REL_PART2' => 'hepsi' ,
   'LBL_ACTION_UPDATE_REL_PART3' => 'ilişkili' ,
   'LBL_ACTION_NEW' => 'Yeni oluştur' ,
   'LBL_RECORD' => 'kayıt' ,
   'LBL_ACTION_NEW_REL' => 'Yeni oluştur' ,
   'LBL_ACTION_NEW_REL_TITLE' => 'Hedef modül ile ilişkili bir modül ile alakalı bir kayıt oluştur' ,
   'LBL_RELATED_RECORD' => 'kayıt' ,
   'LBL_NEXT_BUTTON' => 'Sonraki' ,
   'LBL_PREVIOUS_BUTTON' => 'Önceki' ,
   'LBL_LIST_ACTION_DESCRIPTION' => 'Gerçekleştirilecek Aksiyonlar:' ,
   'LBL_INVITEES' => 'Davetliler' ,
   'LBL_DETAILS' => 'Detaylar' ,
   'LBL_SELECT_VALUE' => 'Geçerli bir değer seçmelisiniz.' ,
   'LBL_SELECT_MODULE' => 'Bir modül seçmelisiniz.' ,
   'LBL_SELECT_RELATED_MODULE' => 'İlişkili bir modül seçmelisiniz.' ,
   'LBL_SELECT_CHECKED_FIELDS' => 'Tüm seçili alanlar için birer değer seçmelisiniz' ,
   'LBL_SET' => 'Ayarla' ,
   'LBL_AS' => 'olarak' ,
   'LBL_SHOW' => 'Göster' ,
   'LBL_TITLE_ADVANCED' => 'Gelişmiş İlişkili Modül Opsiyonları' ,
   'LBL_BY' => 'ile' ,
   'LBL__S' => ' s' ,
   'LBL_FILTER_RELATED' => 'Filtre İle İlişkili' ,
   'LBL_ASSOCIATED_WITH' => ' ilgili ile ilişkili' ,
   'LBL_ACTION_ERROR' => 'Bu aksiyon hatalar içeriyor ve çalıştırılamaz.' );

?>
