<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ProductCategories/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Ürün Kategorileri' ,
   'LBL_MODULE_TITLE' => 'Ürün Kategorileri: Ana Sayfa' ,
   'LBL_SEARCH_FORM_TITLE' => 'Ürün Tipi Arama' ,
   'LBL_LIST_FORM_TITLE' => 'Ürün Kategori Listesi' ,
   'LBL_PRODUCTCATEGORY' => 'Ürün Kategorisi:' ,
   'LBL_LIST_NAME' => 'Ürün Kategorisi' ,
   'LBL_LIST_DESCRIPTION' => 'Tanım' ,
   'LBL_ID' => 'ID' ,
   'LBL_NAME' => 'Ürün Kategorisi:' ,
   'LBL_DESCRIPTION' => 'Tanım:' ,
   'LBL_LIST_LIST_ORDER' => 'Sıra' ,
   'LBL_LIST_ORDER' => 'Sıra:' ,
   'LNK_PRODUCT_LIST' => 'Ürün Kataloğu' ,
   'LNK_NEW_PRODUCT' => 'Katalog için Ürün Oluştur' ,
   'LNK_NEW_MANUFACTURER' => 'Üreticiler' ,
   'LNK_NEW_SHIPPER' => 'Nakliyat Sağlayıcıları' ,
   'LNK_NEW_PRODUCT_CATEGORY' => 'Ürün Kategorileri' ,
   'LNK_NEW_PRODUCT_TYPE' => 'Ürün Tipleri' ,
   'NTC_DELETE_CONFIRMATION' => 'Bu kaydı silmek istediğinizden emin misiniz?' ,
   'ERR_DELETE_RECORD' => 'Ürün tipini silmek için kayıt numarasını belirtmeniz gerekmektedir.' ,
   'NTC_LIST_ORDER' => 'Bu ürün kategorisinin, Ürün Kategorisi açılır-listesinde görünmesini istediğiniz sırayı belirleyin' ,
   'LNK_IMPORT_PRODUCT_CATEGORIES' => 'Ürün Kategori Verilerini Yükle' ,
   'LBL_DISABLE_ALERT' => 'Bu geçerli bir Üst Kategori değildir' ,
   'NTC_DELETE_PRUNE_CONFIRMATION' => 'Bu kategori ile onun alt kategorilerini ve ürünleri silmek istediğinizden emin misiniz?' ,
   'NTC_DELETE_GRAFT_CONFIRMATION' => 'Bu kategoriyi silmek istediğinizden emin misiniz? Tüm alt kategoriler ve ürünler aynen kalacak.' ,
   'LBL_PARENT_NAME' => 'Üst Kategori:' ,
   'LBL_CATEGORIES' => 'Kategoriler' ,
   'LBL_EDITLAYOUT' => '' ,
   'LBL_CREATED_ID' => 'Oluşturan ID' ,
   'LBL_MODIFIED_ID' => 'Değiştiren ID' ,
   'LBL_PARENT_CATEGORY' => 'Üst Kategori' ,
   'LBL_EXPORT_PARENT_ID' => 'Üst Kategori ID&#39;si' ,
   'LBL_EXPORT_MODIFIED_USER_ID' => 'Değiştirilmiş Kullanıcı ID&#39;si' ,
   'LBL_EXPORT_CREATED_BY' => 'Oluşturan ID' );

?>
