<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Notifications/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ASSIGNED_TO_ID' => 'Atanan Kullanıcı ID' ,
   'LBL_ASSIGNED_TO_NAME' => 'Atanan Kişi' ,
   'LBL_ID' => 'ID' ,
   'LBL_DATE_ENTERED' => 'Oluşturulma Tarihi' ,
   'LBL_DATE_MODIFIED' => 'Değiştirilme Tarihi' ,
   'LBL_MODIFIED' => 'Değiştiren' ,
   'LBL_MODIFIED_ID' => 'Değiştiren ID' ,
   'LBL_MODIFIED_NAME' => 'Değiştiren Kişinin İsmi' ,
   'LBL_CREATED' => 'Oluşturan' ,
   'LBL_CREATED_ID' => 'Oluşturan ID' ,
   'LBL_DESCRIPTION' => 'Tanım' ,
   'LBL_DELETED' => 'Silindi' ,
   'LBL_NAME' => 'İsim' ,
   'LBL_CREATED_USER' => 'Oluşturan Kullanıcı' ,
   'LBL_MODIFIED_USER' => 'Değiştiren Kullanıcı' ,
   'LBL_TEAM' => 'Takım' ,
   'LBL_TEAMS' => 'Takımlar' ,
   'LBL_TEAM_ID' => 'Takım ID' ,
   'LBL_LIST_FORM_TITLE' => 'Uyarılar Listesi' ,
   'LBL_MODULE_NAME' => 'Uyarılar' ,
   'LBL_MODULE_TITLE' => 'Uyarılar' ,
   'LBL_HOMEPAGE_TITLE' => 'Uyarılarım' ,
   'LNK_NEW_RECORD' => 'Uyarı Oluştur' ,
   'LNK_LIST' => 'Uyarılar' ,
   'LBL_SEARCH_FORM_TITLE' => 'Uyarı Arama' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => 'Tarihçeyi Gör' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Aktiviteler' ,
   'LBL_ASX_NOTIFICATIONS_SUBPANEL_TITLE' => 'Uyarılar' ,
   'LBL_NEW_FORM_TITLE' => 'Yeni Uyarılar' ,
   'LBL_IS_READ' => 'Okundu' );

?>
