<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Sync/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Senkronizasyon' ,
   'LBL_MODULE_TITLE' => 'Senkronizasyon: Ana' ,
   'LBL_GO_ONLINE' => 'Çevrimiçi Ol' ,
   'LBL_SYNC_AVAILABLE' => 'Sunucunun Kullanabilirliğini Kontrol Et' ,
   'LBL_CHECKING_SYNC_AVAILABLE' => 'Sunucunun Kullanabilirliği Kontrol Ediliyor...' ,
   'LBL_SERVER_AVAILABLE' => 'Sunucu Kullanılabilir' ,
   'LBL_SERVER_UNAVAILABLE' => 'Sunucu Mevcut Değil - Lütfen internete bağlı olduğunuzdan emin olun' ,
   'LBL_START_SYNC' => 'Senkronizasyonu Başlat' ,
   'LBL_SYNC_SETUP' => 'Senkronizasyon Ayarı' ,
   'LBL_PROMPT' => 'İstem' ,
   'LBL_ACCEPT_SERVER' => 'Sunucu Kazandı' ,
   'LBL_ACCEPT_CLIENT' => 'İstemci Kazandı' ,
   'LBL_CLEAN_SYNC' => 'Senkronizasyonu Temizle:' ,
   'LBL_CLEAN_ALERT' => 'Senkronizasyon Temizle uygulanırsa Client makinesinde bulunan tüm kayıtlar silinecektir' ,
   'LBL_INITIAL_SYNC_MESSAGE' => 'Çevrimdışı istemci yüklediniz. Lütfen senkronizasyon işleminin başlaması için aşağıdaki butona basın.' ,
   'LBL_POWERED_BY_SUGAR' => 'SugarCRM Tarafından Geliştirildi' );

?>
