<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/TimePeriods/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_NAME' => 'ID' ,
   'LBL_TP_NAME' => 'Zaman Aralığı' ,
   'LBL_TP_START_DATE' => 'Başlangıç Tarihi' ,
   'LBL_TP_END_DATE' => 'Bitiş Tarihi' ,
   'LBL_TP_FISCAL_YEAR' => 'Mali Yıl' ,
   'LBL_MODULE_NAME' => 'Zaman Aralıkları' ,
   'LBL_MODULE_TITLE' => 'Zaman Aralıkları: Ana Sayfa' ,
   'LBL_SEARCH_FORM_TITLE' => 'Zaman Aralığı Arama' ,
   'LBL_LIST_FORM_TITLE' => 'Zaman Aralıkları' ,
   'LBL_NEW_FORM_TITLE' => 'Yeni Zaman Aralığı' ,
   'LNK_NEW_TIMEPERIOD' => 'Zaman Aralığı Oluştur' ,
   'LNK_TIMEPERIOD_LIST' => 'Zaman Aralığını Gör' ,
   'LBL_TP_IS_FISCAL_YEAR' => 'Mali Yıl?' ,
   'LBL_PARENT_ID' => 'Üst ID' ,
   'LBL_CREATED_BY' => 'Oluşturan' ,
   'LBL_DATE_ENTERED' => 'Giriş Tarihi' ,
   'LBL_DATE_MODIFIED' => 'Değiştirilme Tarihi' ,
   'LBL_DELETED' => 'Silindi' ,
   'LBL_SEARCH_TP_NAME' => 'Zaman Aralığı' ,
   'LBL_SEARCH_TP_START_DATE' => 'Başlangıç Tarihi' ,
   'LBL_SEARCH_TP_END_DATE' => 'Bitiş Tarihi' ,
   'ERR_TIME_PERIOD_DATE_RANGE' => 'Zaman aralığı bitiş tarihi başlangıç tarihinden sonra olmalıdır.' ,
   'LBL_EDITLAYOUT' => 'Yerleşimi Değiştir' );

?>
