<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ProspectLists/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Hedef Listeler' ,
   'LBL_MODULE_ID' => 'Hedef Listeler' ,
   'LBL_MODULE_TITLE' => 'Hedef Listeleri: Ana Sayfa' ,
   'LBL_SEARCH_FORM_TITLE' => 'Hedef Listeleri Arama' ,
   'LBL_LIST_FORM_TITLE' => 'Hedef Listeler' ,
   'LBL_PROSPECT_LIST_NAME' => 'Hedef Listesi:' ,
   'LBL_NAME' => 'İsim' ,
   'LBL_ENTRIES' => 'Toplam Kayıtlar' ,
   'LBL_LIST_PROSPECT_LIST_NAME' => 'Hedef Liste' ,
   'LBL_LIST_ENTRIES' => 'Listedeki Hedefler' ,
   'LBL_LIST_DESCRIPTION' => 'Tanım' ,
   'LBL_LIST_TYPE_NO' => 'Tipi' ,
   'LBL_LIST_END_DATE' => 'Bitiş Tarihi' ,
   'LBL_DATE_ENTERED' => 'Oluşturulma Tarihi' ,
   'LBL_MARKETING_ID' => 'Pazarlama ID' ,
   'LBL_DATE_MODIFIED' => 'Değiştirilme Tarihi' ,
   'LBL_MODIFIED' => 'Değiştiren' ,
   'LBL_CREATED' => 'Oluşturan' ,
   'LBL_TEAM' => 'Takım' ,
   'LBL_ASSIGNED_TO' => 'Atanan Kişi' ,
   'LBL_DESCRIPTION' => 'Tanım' ,
   'LNK_NEW_CAMPAIGN' => 'Kampanya Oluştur' ,
   'LNK_CAMPAIGN_LIST' => 'Kampanyalar' ,
   'LNK_NEW_PROSPECT_LIST' => 'Hedef Liste Oluştur' ,
   'LNK_PROSPECT_LIST_LIST' => 'Hedef Listeler' ,
   'LBL_MODIFIED_BY' => 'Değiştiren' ,
   'LBL_CREATED_BY' => 'Oluşturan' ,
   'LBL_DATE_CREATED' => 'Oluşturulma Tarihi' ,
   'LBL_DATE_LAST_MODIFIED' => 'Değiştirilme Tarihi' ,
   'LNK_NEW_PROSPECT' => 'Hedef Oluştur' ,
   'LNK_PROSPECT_LIST' => 'Hedefler' ,
   'LBL_PROSPECT_LISTS_SUBPANEL_TITLE' => 'Hedef Listeler' ,
   'LBL_CONTACTS_SUBPANEL_TITLE' => 'Kontaklar' ,
   'LBL_LEADS_SUBPANEL_TITLE' => 'Potansiyeller' ,
   'LBL_PROSPECTS_SUBPANEL_TITLE' => 'Hedefler' ,
   'LBL_ACCOUNTS_SUBPANEL_TITLE' => 'Müşteriler' ,
   'LBL_COPY_PREFIX' => 'Kopyası' ,
   'LBL_USERS_SUBPANEL_TITLE' => 'Kullanıcılar' ,
   'LBL_TYPE' => 'Tipi' ,
   'LBL_LIST_TYPE' => 'Tipi' ,
   'LBL_LIST_TYPE_LIST_NAME' => 'Tipi' ,
   'LBL_NEW_FORM_TITLE' => 'Yeni Hedef Listesi' ,
   'LBL_MARKETING_NAME' => 'Pazarlama İsmi' ,
   'LBL_MARKETING_MESSAGE' => 'E-Posta Pazarlama Mesajı' ,
   'LBL_DOMAIN_NAME' => 'Alan İsmi' ,
   'LBL_DOMAIN' => 'Bu Alana E-Posta yok' ,
   'LBL_LIST_PROSPECTLIST_NAME' => 'İsim' ,
   'LBL_MORE_DETAIL' => 'Daha Fazla Detay' );

?>
