/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
var TextField=function(options,parent){Field.call(this,options,parent);this.maxCharacters=null;TextField.prototype.initObject.call(this,options);};TextField.prototype=new Field();TextField.prototype.type='TextField';TextField.prototype.initObject=function(options){var defaults={maxCharacters:0,value:"",initialValue:""};$.extend(true,defaults,options);this.setMaxCharacters(defaults.maxCharacters).setInitialValue(defaults.initialValue).setValue(defaults.value);};TextField.prototype.setMaxCharacters=function(value){this.maxCharacters=value;return this;};TextField.prototype.createHTML=function(){var fieldLabel,textInput,required='',readAtt;Field.prototype.createHTML.call(this);if(this.required){required='<i>*</i> ';}
fieldLabel=this.createHTMLElement('span');fieldLabel.className='adam-form-label';fieldLabel.innerHTML=this.label+': '+required;fieldLabel.style.width=this.parent.labelWidth;this.html.appendChild(fieldLabel);textInput=this.createHTMLElement('input');textInput.type="text";textInput.id=this.name;textInput.value=this.value||"";if(this.fieldWidth){textInput.style.width=this.fieldWidth;}
if(this.readOnly){readAtt=document.createAttribute('readonly');textInput.setAttributeNode(readAtt);}
this.html.appendChild(textInput);if(this.errorTooltip){this.html.appendChild(this.errorTooltip.getHTML());}
if(this.helpTooltip){this.html.appendChild(this.helpTooltip.getHTML());}
this.labelObject=fieldLabel;this.controlObject=textInput;return this.html;};TextField.prototype.attachListeners=function(){var self=this;if(this.controlObject){$(this.controlObject).change(function(){self.setValue(this.value,true);self.onChange();}).keydown(function(e){e.stopPropagation();});}
return this;};TextField.prototype.disable=function(){this.labelObject.className='adam-form-label-disabled';this.controlObject.disabled=true;if(!this.oldRequiredValue){this.oldRequiredValue=this.required;}
this.setRequired(false);$(this.controlObject).removeClass('required');};TextField.prototype.enable=function(){this.labelObject.className='adam-form-label';this.controlObject.disabled=false;if(this.oldRequiredValue){this.setRequired(this.oldRequiredValue);}};var ComboboxField=function(options,parent){Field.call(this,options,parent);this.options=[];this.related=null;ComboboxField.prototype.initObject.call(this,options);};ComboboxField.prototype=new Field();ComboboxField.prototype.type='ComboboxField';ComboboxField.prototype.initObject=function(options){var defaults={options:[],related:null};$.extend(true,defaults,options);this.setOptions(defaults.options).setRelated(defaults.related);};ComboboxField.prototype.setOptions=function(data){var i;this.options=data;if(this.html){for(i=0;i<this.options.length;i+=1){this.controlObject.appendChild(this.generateOption(this.options[i]));}
if(!this.value){this.value=this.controlObject.value;}}
return this;};ComboboxField.prototype.setRelated=function(data){this.related=data;return this;};ComboboxField.prototype.createHTML=function(){var fieldLabel,selectInput,required='',opt,i,disableAtt;Field.prototype.createHTML.call(this);if(this.required){required='<i>*</i> ';}
fieldLabel=this.createHTMLElement('span');fieldLabel.className='adam-form-label';fieldLabel.innerHTML=this.label+': '+required;fieldLabel.style.width=this.parent.labelWidth;this.html.appendChild(fieldLabel);selectInput=this.createHTMLElement('select');selectInput.id=this.name;for(i=0;i<this.options.length;i+=1){selectInput.appendChild(this.generateOption(this.options[i]));}
if(!this.value){this.value=selectInput.value;}
if(this.fieldWidth){selectInput.style.width=this.fieldWidth;}
if(this.readOnly){disableAtt=document.createAttribute('disabled');selectInput.setAttributeNode(disableAtt);}
this.html.appendChild(selectInput);if(this.errorTooltip){this.html.appendChild(this.errorTooltip.getHTML());}
if(this.helpTooltip){this.html.appendChild(this.helpTooltip.getHTML());}
this.labelObject=fieldLabel;this.controlObject=selectInput;return this.html;};ComboboxField.prototype.removeOptions=function(){if(this.options){while(this.controlObject.firstChild){this.controlObject.removeChild(this.controlObject.firstChild);}
this.options=[];}
return this;};ComboboxField.prototype.generateOption=function(item){var out,selected='',value,text;out=this.createHTMLElement('option');if(typeof item==='object'){value=item.value;text=item.text;}else{value=item;}
out.selected=this.value===value;out.value=value;out.label=text||value;out.appendChild(document.createTextNode(text||value));return out;};ComboboxField.prototype.attachListeners=function(){var self=this;if(this.controlObject){$(this.controlObject).change(function(e){var oldValue=self.value;self.setValue(this.value,true);self.onChange(this.value,oldValue);});}
return this;};ComboboxField.prototype.disable=function(){this.labelObject.className='adam-form-label-disabled';this.controlObject.disabled=true;if(!this.oldRequiredValue){this.oldRequiredValue=this.required;}
this.setRequired(false);$(this.controlObject).removeClass('required');};ComboboxField.prototype.enable=function(){this.labelObject.className='adam-form-label';this.controlObject.disabled=false;if(this.oldRequiredValue){this.setRequired(this.oldRequiredValue);}};var TextareaField=function(options,parent){Field.call(this,options,parent);this.fieldHeight=null;TextareaField.prototype.initObject.call(this,options);};TextareaField.prototype=new Field();TextareaField.prototype.type="TextareaField";TextareaField.prototype.initObject=function(options){var defaults={fieldHeight:null,value:"",initialValue:""};$.extend(true,defaults,options);this.setFieldHeight(defaults.fieldHeight).setInitialValue(defaults.initialValue).setValue(defaults.value);};TextareaField.prototype.setFieldHeight=function(height){this.fieldHeight=height;return this;};TextareaField.prototype.createHTML=function(){var fieldLabel,textInput,required='',readAtt;Field.prototype.createHTML.call(this);if(this.required){required='<i>*</i> ';}
fieldLabel=this.createHTMLElement('span');fieldLabel.className='adam-form-label';fieldLabel.innerHTML=this.label+': '+required;fieldLabel.style.width=this.parent.labelWidth;fieldLabel.style.verticalAlign='top';this.html.appendChild(fieldLabel);textInput=this.createHTMLElement('textarea');textInput.id=this.name;textInput.value=this.value;if(this.fieldWidth){textInput.style.width=this.fieldWidth;}
if(this.fieldHeight){textInput.style.height=this.fieldHeight;}
if(this.readOnly){readAtt=document.createAttribute('readonly');textInput.setAttributeNode(readAtt);}
this.html.appendChild(textInput);if(this.errorTooltip){this.html.appendChild(this.errorTooltip.getHTML());}
if(this.helpTooltip){this.html.appendChild(this.helpTooltip.getHTML());}
this.controlObject=textInput;return this.html;};TextareaField.prototype.attachListeners=function(){var self=this;if(this.controlObject){$(this.controlObject).change(function(){self.setValue(this.value,true);self.onChange();}).keydown(function(e){e.stopPropagation();});}
return this;};var CheckboxField=function(options,parent){Field.call(this,options,parent);this.defaults={onClick:function(e,ui){}};$.extend(true,this.defaults,options);};CheckboxField.prototype=new Field();CheckboxField.prototype.type='CheckboxField';CheckboxField.prototype.createHTML=function(){var fieldLabel,textInput,required='',readAtt;Field.prototype.createHTML.call(this);if(this.required){required='<i>*</i> ';}
fieldLabel=this.createHTMLElement('span');fieldLabel.className='adam-form-label';fieldLabel.innerHTML=this.label+': '+required;fieldLabel.style.width=this.parent.labelWidth;this.html.appendChild(fieldLabel);textInput=this.createHTMLElement('input');textInput.id=this.name;textInput.type='checkbox';if(this.value){textInput.checked=true;}else{textInput.checked=false;}
if(this.readOnly){readAtt=document.createAttribute('readonly');textInput.setAttributeNode(readAtt);}
this.html.appendChild(textInput);if(this.errorTooltip){this.html.appendChild(this.errorTooltip.getHTML());}
if(this.helpTooltip){this.html.appendChild(this.helpTooltip.getHTML());}
this.labelObject=fieldLabel;this.controlObject=textInput;return this.html;};CheckboxField.prototype.attachListeners=function(){var self=this;if(this.controlObject){if(typeof this.defaults.onClick!=='undefined'&&typeof this.defaults.onClick==='function'){$(this.controlObject).on('click',function(e,ui){return self.defaults.onClick();});}
$(this.controlObject).change(function(a,b){var val;if(this.checked){val=true;}else{val=false;}
self.setValue(val,true);self.onChange();});}
return this;};CheckboxField.prototype.getObjectValue=function(){var response={};if(this.value){response[this.name]=true;}else{response[this.name]=false;}
return response;};CheckboxField.prototype.evalRequired=function(){var response=true;if(this.required){response=this.value;if(!response){$(this.controlObject).addClass('required');}else{$(this.controlObject).removeClass('required');}}
return response;};CheckboxField.prototype.disable=function(){this.labelObject.className='adam-form-label-disabled';this.controlObject.disabled=true;if(!this.oldRequiredValue){this.oldRequiredValue=this.required;}
this.setRequired(false);$(this.controlObject).removeClass('required');};CheckboxField.prototype.enable=function(){this.labelObject.className='adam-form-label';this.controlObject.disabled=false;if(this.oldRequiredValue){this.setRequired(this.oldRequiredValue);}};var RadiobuttonField=function(options,parent){Field.call(this,options,parent);this.defaults={options:{},onClick:function(e,ui){}};$.extend(true,this.defaults,options);};RadiobuttonField.prototype=new Field();RadiobuttonField.prototype.type='RadiobuttonField';RadiobuttonField.prototype.createHTML=function(){var fieldLabel,textInput,required='',readAtt;Field.prototype.createHTML.call(this);if(this.required){required='<i>*</i> ';}
fieldLabel=this.createHTMLElement('span');fieldLabel.className='adam-form-label';textInput=this.createHTMLElement('input');textInput.name=this.name;textInput.type='radio';textInput.value=this.value;if(typeof(this.defaults.labelAlign)==='undefined'||this.defaults.labelAlign==='left'){fieldLabel.style.width=this.parent.labelWidth;fieldLabel.innerHTML=this.label+': '+required;fieldLabel.style.verticalAlign='top';fieldLabel.style.width=this.parent.labelWidth;this.html.appendChild(fieldLabel);this.html.appendChild(textInput);}else if(this.defaults.labelAlign==='right'){fieldLabel.innerHTML='&nbsp;'+this.label+required;textInput.style.marginLeft=(this.defaults.marginLeft)?this.defaults.marginLeft+'px':'0px';fieldLabel.style.width=this.parent.labelWidth;this.html.appendChild(textInput);this.html.appendChild(fieldLabel);}
if(this.value){textInput.checked=true;}else{textInput.checked=false;}
if(this.readOnly){readAtt=document.createAttribute('readonly');textInput.setAttributeNode(readAtt);}
if(this.errorTooltip){this.html.appendChild(this.errorTooltip.getHTML());}
if(this.helpTooltip){this.html.appendChild(this.helpTooltip.getHTML());}
this.controlObject=textInput;return this.html;};RadiobuttonField.prototype.attachListeners=function(){var self=this;if(this.controlObject){if(typeof this.defaults.onClick!=='undefined'&&typeof this.defaults.onClick==='function'){$(this.controlObject).on('click',function(e,ui){return self.defaults.onClick();});}
$(this.controlObject).change(function(a,b){self.onChange();});}
return this;};RadiobuttonField.prototype.getObjectValue=function(){return this.value;};RadiobuttonField.prototype.evalRequired=function(){var response=true;if(this.required){response=this.value;if(!response){$(this.controlObject).addClass('required');}else{$(this.controlObject).removeClass('required');}}
return response;};RadiobuttonField.prototype._setValueToControl=function(value){if(this.html&&this.controlObject){this.controlObject.checked=this.value;}
return this;};var LabelField=function(options,parent){Field.call(this,options,parent);this.submit=false;this.defaults={options:{marginLeft:10}};$.extend(true,this.defaults,options);};LabelField.prototype=new Field();LabelField.prototype.type='LabelField';LabelField.prototype.createHTML=function(){var fieldLabel;Field.prototype.createHTML.call(this);fieldLabel=this.createHTMLElement('span');fieldLabel.innerHTML=this.label+':';fieldLabel.style.verticalAlign='top';fieldLabel.style.marginLeft=this.defaults.options.marginLeft+'px';this.html.appendChild(fieldLabel);return this.html;};var HiddenField=function(options,parent){Field.call(this,options,parent);};HiddenField.prototype=new Field();HiddenField.prototype.type='HiddenField';HiddenField.prototype.createHTML=function(){Element.prototype.createHTML.call(this);return this.html;};var EmailGroupField=function(options,parent){Field.call(this,options,parent);};EmailGroupField.prototype=new Field();EmailGroupField.prototype.type='EmailGroupField';var DateField=function(options,parent){Field.call(this,options,parent);this.maxCharacters=null;DateField.prototype.initObject.call(this,options);};DateField.prototype=new Field();DateField.prototype.type='TextField';DateField.prototype.initObject=function(options){var defaults={maxCharacters:0};$.extend(true,defaults,options);this.setMaxCharacters(defaults.maxCharacters);};DateField.prototype.setMaxCharacters=function(value){this.maxCharacters=value;return this;};DateField.prototype.createHTML=function(){var fieldLabel,textInput,required='',readAtt;Field.prototype.createHTML.call(this);if(this.required){required='<i>*</i> ';}
fieldLabel=this.createHTMLElement('span');fieldLabel.className='adam-form-label';fieldLabel.innerHTML=this.label+': '+required;fieldLabel.style.width=this.parent.labelWidth;this.html.appendChild(fieldLabel);textInput=this.createHTMLElement('input');textInput.id=this.name;textInput.value=this.value||"";$(textInput).datepicker();if(this.fieldWidth){textInput.style.width=this.fieldWidth;}
if(this.readOnly){readAtt=document.createAttribute('readonly');textInput.setAttributeNode(readAtt);}
this.html.appendChild(textInput);if(this.errorTooltip){this.html.appendChild(this.errorTooltip.getHTML());}
if(this.helpTooltip){this.html.appendChild(this.helpTooltip.getHTML());}
this.labelObject=fieldLabel;this.controlObject=textInput;return this.html;};DateField.prototype.attachListeners=function(){var self=this;if(this.controlObject){$(this.controlObject).change(function(){self.setValue(this.value,true);self.onChange();}).keydown(function(e){e.stopPropagation();});}
return this;};DateField.prototype.disable=function(){this.labelObject.className='adam-form-label-disabled';this.controlObject.disabled=true;if(!this.oldRequiredValue){this.oldRequiredValue=this.required;}
this.setRequired(false);$(this.controlObject).removeClass('required');$(this.controlObject).datepicker('hide');};DateField.prototype.enable=function(){this.labelObject.className='adam-form-label';this.controlObject.disabled=false;if(this.oldRequiredValue){this.setRequired(this.oldRequiredValue);}};var NumberField=function(options,parent){Field.call(this,options,parent);this.maxCharacters=null;NumberField.prototype.initObject.call(this,options);};NumberField.prototype=new Field();NumberField.prototype.type='TextField';NumberField.prototype.initObject=function(options){var defaults={maxCharacters:0};$.extend(true,defaults,options);this.setMaxCharacters(defaults.maxCharacters);};NumberField.prototype.setMaxCharacters=function(value){this.maxCharacters=value;return this;};NumberField.prototype.createHTML=function(){var fieldLabel,textInput,required='',readAtt;Field.prototype.createHTML.call(this);if(this.required){required='<i>*</i> ';}
fieldLabel=this.createHTMLElement('span');fieldLabel.className='adam-form-label';fieldLabel.innerHTML=this.label+': '+required;fieldLabel.style.width=this.parent.labelWidth;this.html.appendChild(fieldLabel);textInput=this.createHTMLElement('input');textInput.type="number";textInput.id=this.name;textInput.value=this.value||"";textInput.min="0";if(this.fieldWidth){textInput.style.width=this.fieldWidth;}
if(this.readOnly){readAtt=document.createAttribute('readonly');textInput.setAttributeNode(readAtt);}
this.html.appendChild(textInput);if(this.errorTooltip){this.html.appendChild(this.errorTooltip.getHTML());}
if(this.helpTooltip){this.html.appendChild(this.helpTooltip.getHTML());}
this.labelObject=fieldLabel;this.controlObject=textInput;return this.html;};NumberField.prototype.attachListeners=function(){var self=this;if(this.controlObject){$(this.controlObject).change(function(){self.setValue(this.value,true);self.onChange();}).keydown(function(e){e.stopPropagation();});}
$(this.controlObject).on('keydown',function(event){event.stopPropagation();if(event.keyCode===46||event.keyCode===8||event.keyCode===9||event.keyCode===27||event.keyCode===13||(event.keyCode===65&&event.ctrlKey===true)||(event.keyCode>=35&&event.keyCode<=39)){return;}else{if(event.shiftKey||(event.keyCode<48||event.keyCode>57)&&(event.keyCode<96||event.keyCode>105)){event.preventDefault();}}}).on('keyup',function(e){e.stopPropagation();});return this;};NumberField.prototype.disable=function(){this.labelObject.className='adam-form-label-disabled';this.controlObject.disabled=true;if(!this.oldRequiredValue){this.oldRequiredValue=this.required;}
this.setRequired(false);$(this.controlObject).removeClass('required');};NumberField.prototype.enable=function(){this.labelObject.className='adam-form-label';this.controlObject.disabled=false;if(this.oldRequiredValue){this.setRequired(this.oldRequiredValue);}};var CheckboxGroup=function(options,parent){Field.call(this,options,parent);this.controlObject={};CheckboxGroup.prototype.initObject.call(this,options);};CheckboxGroup.prototype=new Field();CheckboxGroup.prototype.type='CheckboxGroup';CheckboxGroup.prototype.initObject=function(options){var defaults={items:[]};$.extend(true,defaults,options);this.items=defaults.items;};CheckboxGroup.prototype.createHTML=function(){var fieldLabel,input,required='',readAtt,div,i,text,ul,li,root=this,object;Field.prototype.createHTML.call(this);if(this.required){required='<i>*</i> ';}
div=this.createHTMLElement('div');div.style.display='inline-block';div.style.width="30%";div.style.verticalAlign='top';fieldLabel=this.createHTMLElement('span');fieldLabel.className='adam-form-label';fieldLabel.innerHTML=this.label+': '+required+'&nbsp;&nbsp;&nbsp;&nbsp;';fieldLabel.style.width=this.parent.labelWidth;div.appendChild(fieldLabel);this.html.appendChild(div);div=this.createHTMLElement('div');div.style.display='inline-block';div.style.width="40%";ul=this.createHTMLElement('ul');for(i=0;i<this.items.length;i+=1){li=this.createHTMLElement('li');li.style.listStyleType='none';input=this.createHTMLElement('input');input.id=this.items[i].value;input.type='checkbox';if(this.items[i].checked){input.checked=true;}else{input.checked=false;}
if(this.readOnly){readAtt=document.createAttribute('readonly');input.setAttributeNode(readAtt);}
li.appendChild(input);object={'control':input};if(this.items[i].checked){object.checked=true;}
this.controlObject[this.items[i].value]=object;text=document.createElement("Label");text.innerHTML=' &nbsp;&nbsp;'+this.items[i].text;li.appendChild(text);ul.appendChild(li);$(input).change(function(){if(this.checked){root.controlObject[$(this).attr('id')].checked=true;}else{root.controlObject[$(this).attr('id')].checked=false;}});}
div.appendChild(ul);this.html.appendChild(div);if(this.errorTooltip){this.html.appendChild(this.errorTooltip.getHTML());}
if(this.helpTooltip){this.html.appendChild(this.helpTooltip.getHTML());}
this.labelObject=fieldLabel;return this.html;};CheckboxGroup.prototype.attachListeners=function(){var self=this,i,control;return this;};CheckboxGroup.prototype.getObjectValue=function(){var response={},i,control,array=[];$.each(this.controlObject,function(key,value){if(value.checked){array.push(key);}});response[this.name]=array;return response;};CheckboxGroup.prototype.evalRequired=function(){var response=true;if(this.required){response=this.value;if(!response){$(this.controlObject).addClass('required');}else{$(this.controlObject).removeClass('required');}}
return response;};CheckboxGroup.prototype.disable=function(){this.labelObject.className='adam-form-label-disabled';this.controlObject.disabled=true;if(!this.oldRequiredValue){this.oldRequiredValue=this.required;}
this.setRequired(false);$(this.controlObject).removeClass('required');};CheckboxGroup.prototype.enable=function(){this.labelObject.className='adam-form-label';this.controlObject.disabled=false;if(this.oldRequiredValue){this.setRequired(this.oldRequiredValue);}};