<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Quotas/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Kotalar' ,
   'LBL_MODULE_TITLE' => 'Kotalar: Ana Sayfa' ,
   'LBL_LIST_FORM_TITLE' => 'Kota Listesi' ,
   'LBL_QUOTA' => 'Kota:' ,
   'LBL_DIRECT_REPORT' => 'Doğrudan Rapor' ,
   'LBL_QUOTA_AMOUNT' => 'Kota Miktarı' ,
   'LBL_LAST_MODIFIED' => 'Değiştirilme Tarihi' ,
   'LBL_COMMIT_STATUS' => 'Onay Durumu' ,
   'LBL_COMMITTED' => 'Atanmış' ,
   'LBL_NOT_COMMITTED' => 'Beklemede' ,
   'LBL_MODULE_FORECASTS_NAME' => 'Tahminler' ,
   'LNK_FORECAST_LIST' => 'Tahmin' ,
   'LNK_FORECAST_HISTORY' => 'Tahmin Tarihçesi' ,
   'LNK_UPD_FORECAST' => 'Tahmin Çalışma Sayfası' ,
   'LNK_QUOTA' => 'Kotalar' ,
   'LBL_NAME' => 'İsim:' ,
   'LBL_TIME_PERIOD' => 'Zaman Aralığı:' ,
   'LBL_SELECT_TIME_PERIOD' => 'Zaman Aralığı Seçin...' ,
   'LBL_AMOUNT' => 'Tutar:' ,
   'LBL_CURRENCY' => 'Para Birimi:' ,
   'LBL_COMMIT' => 'Onay:' ,
   'LBL_SELECT_USER' => 'Kullanıcı Seçin...' ,
   'LBL_NO_QUOTAS_TIMEPERIOD' => 'Bu zaman aralığında doğrudan raporlar için herhangi bir kota girilmedi.' ,
   'LBL_CURRENT_USER_QUOTA' => 'Bu zaman aralığı için ayırmış olduğunuz kota:' ,
   'LBL_CURRENT_USER_NO_QUOTA' => 'Bu zaman aralığı için herhangi bir kota ayırmadınız.' ,
   'LBL_USER_ID' => 'Kullanıcı ID' ,
   'LBL_EDITLAYOUT' => 'YerleşimiDeğiştir' );

?>
