<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Charts/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'ERR_NO_OPPS' => 'Lütfen, Fırsat grafiğini görmek için birkaç Fırsat oluşturun.' ,
   'LBL_ALL_OPPORTUNITIES' => 'Tüm fırsatların toplam miktarı' ,
   'LBL_CHART_TYPE' => 'Grafik Türü:' ,
   'LBL_CREATED_ON' => 'Son Çalışma' ,
   'LBL_CLOSE_DATE_START' => 'Tahmini Kapanış Tarihi - Kimden:' ,
   'LBL_CLOSE_DATE_END' => 'Tahmini Kapanış Tarihi - Kime:' ,
   'LBL_DATE_END' => 'Bitiş Tarihi:' ,
   'LBL_DATE_RANGE_TO' => 'kadar' ,
   'LBL_DATE_RANGE' => 'Tarih aralığı' ,
   'LBL_DATE_START' => 'Başlangıç Tarihi:' ,
   'LBL_EDIT' => 'Değiştir' ,
   'LBL_LEAD_SOURCE_BY_OUTCOME_DESC' => 'Seçili Kaynak, Sonuç ve Kullanıcılara göre toplam fırsat miktarını gösterir. Sonuç, Kapandı-Kazanıldı, Kapandı-Kaybedildi ya da herhangi başka bir değer içeren satış aşamasına göredir.' ,
   'LBL_LEAD_SOURCE_BY_OUTCOME' => 'Potansiyel Kaynağına, Sonuçlara göre Tüm Fırsatlar' ,
   'LBL_LEAD_SOURCE_FORM_DESC' => 'Seçilen kullanıcılar için, seçilen potansiyel kaynağına göre fırsatlar miktarını gösterir.' ,
   'LBL_LEAD_SOURCE_FORM_TITLE' => 'Potansiyel Kaynaklarına göre Bütün Fırsatlar' ,
   'LBL_LEAD_SOURCE_OTHER' => 'Diğer' ,
   'LBL_LEAD_SOURCES' => 'Potansiyel Kaynaklar:' ,
   'LBL_MODULE_NAME' => 'Gösterge Panosu' ,
   'LBL_MODULE_TITLE' => 'Gösterge Panosu: Ana Sayfa' ,
   'LBL_MONTH_BY_OUTCOME_DESC' => 'Tahmini kapanış tarihi ile girilen tarih aralığında kalan aylara göre seçili kullanıcılara ve sonuç şekline göre toplam fırsat miktarını gösterir. Sonuç, Kapandı-Kazanıldı, Kapandı-Kaybedildi ya da herhangi başka bir değer içeren satış aşamasına göredir.' ,
   'LBL_NUMBER_OF_OPPS' => 'Fırsat Sayısı' ,
   'LBL_OPP_SIZE' => 'Fırsat büyüklüğü' ,
   'LBL_OPP_THOUSANDS' => 'Bin' ,
   'LBL_OPPS_IN_LEAD_SOURCE' => 'fırsatlar için Potansiyel Kaynağı' ,
   'LBL_OPPS_IN_STAGE' => ' satış aşaması şu olanlar:' ,
   'LBL_OPPS_OUTCOME' => ' çıktısı şu olan:' ,
   'LBL_OPPS_WORTH' => 'fırsatların değeri' ,
   'LBL_PIPELINE_FORM_TITLE_DESC' => 'Tahmini sonuçlanma tarihi belirtilen tarih aralığında kalan, seçili satış aşamalarına göre fırsatlarınızın toplamını gösterir.' ,
   'LBL_CAMPAIGN_ROI_TITLE_DESC' => 'ROI ye göre Kampanya Yanıtlarını gösterir.' ,
   'LBL_REFRESH' => 'Yenile' ,
   'LBL_ROLLOVER_DETAILS' => 'Detay görmek için bar çubuğu üzerine geliniz.' ,
   'LBL_ROLLOVER_WEDGE_DETAILS' => 'Detay görmek için üzerine geliniz.' ,
   'LBL_SALES_STAGE_FORM_DESC' => 'Tahmini sonuçlanma tarihi belirtilen tarih aralığında kalan, seçili kullanıcılar için satış aşamalarına göre fırsatların toplamını gösterir.' ,
   'LBL_SALES_STAGE_FORM_TITLE' => 'Satış Aşamalarına Göre Satış Olasılıkları' ,
   'LBL_SALES_STAGES' => 'Satış Aşamaları:' ,
   'LBL_TOTAL_PIPELINE' => 'Satış Olasılıkları toplamı' ,
   'LBL_USERS' => 'Kullanıcılar:' ,
   'LBL_YEAR_BY_OUTCOME' => 'Aylık Neticelenme Durumuna Göre Satış Olasılıkları' ,
   'LBL_YEAR' => 'Yıl:' ,
   'LNK_NEW_ACCOUNT' => 'Müşteri Oluştur' ,
   'LNK_NEW_CALL' => 'Tel. Araması Planla' ,
   'LNK_NEW_CASE' => 'Talep Oluştur' ,
   'LNK_NEW_CONTACT' => 'Kontak Oluştur' ,
   'LNK_NEW_ISSUE' => 'Hata Raporla' ,
   'LNK_NEW_LEAD' => 'Potansiyel Oluştur' ,
   'LNK_NEW_MEETING' => 'Toplantı Planla' ,
   'LNK_NEW_NOTE' => 'Not veya Ek Oluştur' ,
   'LNK_NEW_OPPORTUNITY' => 'Fırsat Oluştur' ,
   'LNK_NEW_QUOTE' => 'Teklif Oluştur' ,
   'LNK_NEW_TASK' => 'Görev Oluştur' ,
   'NTC_NO_LEGENDS' => 'Yok' ,
   'LBL_TITLE' => 'Unvan:' ,
   'LBL_MY_MODULES_USED_SIZE' => 'Erişim Sayısı' );

?>
