<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Shippers/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Nakliyeciler' ,
   'LBL_MODULE_TITLE' => 'Nakliyat Firmaları: Ana Sayfa' ,
   'LBL_SEARCH_FORM_TITLE' => 'Nakliyat Firması Arama' ,
   'LBL_LIST_FORM_TITLE' => 'Nakliyat Firma Listesi' ,
   'LBL_NEW_FORM_TITLE' => 'Yeni Nakliyat Firması' ,
   'LBL_SHIPPER' => 'Nakliye Şirketi:' ,
   'LBL_LIST_NAME' => 'Nakliyat Firması:' ,
   'LBL_NAME' => 'Nakliye Şirketi:' ,
   'LBL_LIST_LIST_ORDER' => 'Sıra' ,
   'LBL_LIST_ORDER' => 'Sıra:' ,
   'LBL_LIST_STATUS' => 'Durum' ,
   'LBL_STATUS' => 'Durum:' ,
   'LNK_NEW_SHIPPER' => 'Nakliyat Firma Listesi' ,
   'LNK_NEW_TAXRATE' => 'Vergi Oranı Listesi' ,
   'NTC_DELETE_CONFIRMATION' => 'Bu kaydı silmek istediğinizden emin misiniz?' ,
   'ERR_DELETE_RECORD' => 'Bu nakliyeciyi silmek için kayıt numarası belirmelisiniz.' ,
   'NTC_STATUS' => 'Bu nakliyat firmasının durumunu, İnaktif olarak belirleyerek Nakliyat Firması açılır-listesinden kaldırın' ,
   'NTC_LIST_ORDER' => 'Bu nakliyat firmasının, Nakliyat Firması açılır-listesinde görünmesini istediğiniz sırayı belirleyin' ,
   'LBL_EDITLAYOUT' => 'Yerleşimi Değiştir' ,
   'shipper_status_dom' => array (
      'Active' => 'Aktif' ,
      'Inactive' => 'İnaktif'   ));

?>
