<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN SYNO_DashboardTemplateFilters
 */

class SYNO_DashboardTemplateFilters_sugar extends Basic
{
    public $new_schema = true;
    public $module_dir = 'SYNO_DashboardTemplateFilters';
    public $object_name = 'SYNO_DashboardTemplateFilters';
    public $table_name = 'syno_dashboardtemplatefilters';
    public $importable = false;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $doc_owner;
    public $user_favorites;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $original_filter_id;
    public $filter_definition;
    public $filter_template;
    public $module_name;
    public $disable_row_level_security = true;

    /**
     * This is a deprecated method, please start using __construct() as this
     * method will be removed in a future version.
     *
     * @see __construct
     * @deprecated
     */
    public function SYNO_DashboardTemplateFilters_sugar()
    {
        $GLOBALS['log']->deprecated('Calls to SYNO_DashboardTemplateFilters::SYNO_DashboardTemplateFilters are deprecated.');
        self::__construct();
    }

    public function __construct()
    {
        parent::__construct();
    }

    public function bean_implements($interface)
    {
        switch ($interface) {
            case 'ACL': return true;
        }

        return false;
    }
}
