/*
-- Query: select * from fields_meta_data where custom_module = 'Accounts' and name like 'ct_%'
-- Date: 2017-11-03 10:41
*/
INSERT INTO `fields_meta_data` (`id`,`name`,`vname`,`comments`,`help`,`custom_module`,`type`,`len`,`required`,`default_value`,`date_modified`,`deleted`,`audited`,`massupdate`,`duplicate_merge`,`reportable`,`importable`,`ext1`,`ext2`,`ext3`,`ext4`) VALUES ('Accountsct_hardware_c','ct_hardware_c','LBL_CT_HARDWARE',NULL,NULL,'Accounts','text',NULL,0,NULL,'2017-10-14 16:41:29',0,1,0,1,1,'true',NULL,'4','20',NULL);
INSERT INTO `fields_meta_data` (`id`,`name`,`vname`,`comments`,`help`,`custom_module`,`type`,`len`,`required`,`default_value`,`date_modified`,`deleted`,`audited`,`massupdate`,`duplicate_merge`,`reportable`,`importable`,`ext1`,`ext2`,`ext3`,`ext4`) VALUES ('Accountsct_networking_c','ct_networking_c','LBL_CT_NETWORKING',NULL,NULL,'Accounts','text',NULL,0,NULL,'2017-10-13 14:43:33',0,1,0,1,1,'true',NULL,'4','20',NULL);
INSERT INTO `fields_meta_data` (`id`,`name`,`vname`,`comments`,`help`,`custom_module`,`type`,`len`,`required`,`default_value`,`date_modified`,`deleted`,`audited`,`massupdate`,`duplicate_merge`,`reportable`,`importable`,`ext1`,`ext2`,`ext3`,`ext4`) VALUES ('Accountsct_proj_type_c','ct_proj_type_c','LBL_CT_PROJ_TYPE',NULL,NULL,'Accounts','enum',100,0,NULL,'2017-10-13 14:48:44',0,1,1,1,1,'true','proj_area_list',NULL,NULL,NULL);
INSERT INTO `fields_meta_data` (`id`,`name`,`vname`,`comments`,`help`,`custom_module`,`type`,`len`,`required`,`default_value`,`date_modified`,`deleted`,`audited`,`massupdate`,`duplicate_merge`,`reportable`,`importable`,`ext1`,`ext2`,`ext3`,`ext4`) VALUES ('Accountsct_security_c','ct_security_c','LBL_CT_SECURITY',NULL,NULL,'Accounts','text',NULL,0,NULL,'2017-10-13 14:43:04',0,1,0,1,1,'true',NULL,'4','20',NULL);
INSERT INTO `fields_meta_data` (`id`,`name`,`vname`,`comments`,`help`,`custom_module`,`type`,`len`,`required`,`default_value`,`date_modified`,`deleted`,`audited`,`massupdate`,`duplicate_merge`,`reportable`,`importable`,`ext1`,`ext2`,`ext3`,`ext4`) VALUES ('Accountsct_storage_c','ct_storage_c','LBL_CT_STORAGE',NULL,NULL,'Accounts','text',NULL,0,NULL,'2017-10-13 14:42:37',0,1,0,1,1,'true',NULL,'4','20',NULL);
