<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/CampaignLog/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_LIST_ID' => 'Aday Müşteri Liste ID' ,
   'LBL_ID' => 'ID' ,
   'LBL_TARGET_TRACKER_KEY' => 'Hedef İzleyici Anahtarı' ,
   'LBL_TARGET_ID' => 'Hedef ID' ,
   'LBL_TARGET_TYPE' => 'Hedef Tipi' ,
   'LBL_ACTIVITY_TYPE' => 'Aktivite Tipi' ,
   'LBL_ACTIVITY_DATE' => 'Aktivite Günü' ,
   'LBL_RELATED_ID' => 'İlişkili ID' ,
   'LBL_RELATED_TYPE' => 'İlişkili Tipi' ,
   'LBL_DELETED' => 'Silindi' ,
   'LBL_MODULE_NAME' => 'Kampanya Tarihçesi' ,
   'LBL_LIST_RECIPIENT_EMAIL' => 'Alıcı E-Postası' ,
   'LBL_LIST_RECIPIENT_NAME' => 'Alıcı İsmi' ,
   'LBL_ARCHIVED' => 'Arşivlendi' ,
   'LBL_HITS' => 'Hedefi Tutturma' ,
   'LBL_CAMPAIGN_NAME' => 'İsim:' ,
   'LBL_CAMPAIGN' => 'Kampanya:' ,
   'LBL_NAME' => 'İsim:' ,
   'LBL_INVITEE' => 'Kontaklar' ,
   'LBL_LIST_CAMPAIGN_NAME' => 'Kampanya' ,
   'LBL_LIST_STATUS' => 'Durum' ,
   'LBL_LIST_TYPE' => 'Tipi' ,
   'LBL_LIST_END_DATE' => 'Bitiş Tarihi' ,
   'LBL_DATE_ENTERED' => 'Giriş Tarihi' ,
   'LBL_DATE_MODIFIED' => 'Değiştirilme Tarihi' ,
   'LBL_MODIFIED' => 'Düzenleyen:' ,
   'LBL_CREATED' => 'Oluşturan:' ,
   'LBL_TEAM' => 'Takım:' ,
   'LBL_ASSIGNED_TO' => 'Atanan Kişi:' ,
   'LBL_CAMPAIGN_START_DATE' => 'Başlangıç Tarihi:' ,
   'LBL_CAMPAIGN_END_DATE' => 'Bitiş Tarihi:' ,
   'LBL_CAMPAIGN_STATUS' => 'Durum:' ,
   'LBL_CAMPAIGN_BUDGET' => 'Bütçe:' ,
   'LBL_CAMPAIGN_EXPECTED_COST' => 'Tahmini Maliyet:' ,
   'LBL_CAMPAIGN_ACTUAL_COST' => 'Gerçek Maliyet:' ,
   'LBL_CAMPAIGN_EXPECTED_REVENUE' => 'Beklenen Gelir:' ,
   'LBL_CAMPAIGN_TYPE' => 'Tipi:' ,
   'LBL_CAMPAIGN_OBJECTIVE' => 'Amaç:' ,
   'LBL_CAMPAIGN_CONTENT' => 'Tanım:' ,
   'LBL_CREATED_LEAD' => 'Potansiyel Oluşturuldu' ,
   'LBL_CREATED_CONTACT' => 'Oluşturulan Kontak' ,
   'LBL_CREATED_OPPORTUNITY' => 'Fırsat Oluşturuldu' ,
   'LBL_TARGETED_USER' => 'Hedeflenen Kullanıcı' ,
   'LBL_SENT_EMAIL' => 'E-posta Gönder' ,
   'LBL_LIST_FORM_TITLE' => 'Hedeflenen Kampanyalar' ,
   'LBL_LIST_ACTIVITY_DATE' => 'Aktivite Günü' ,
   'LBL_LIST_CAMPAIGN_OBJECTIVE' => 'Kampanya Hedefi' ,
   'LBL_RELATED' => 'İlişkili' ,
   'LBL_CLICKED_URL_KEY' => 'Tıklanan URL Anahtarı' ,
   'LBL_URL_CLICKED' => 'Tıklanan URL' ,
   'LBL_MORE_INFO' => 'Daha Fazla Bilgi' ,
   'LBL_CAMPAIGNS' => 'Kampanyalar' ,
   'LBL_LIST_MARKETING_NAME' => 'Pazarlama ID' );

?>
