<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ACL/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ALLOW_ALL' => 'Tümü' ,
   'LBL_ALLOW_NONE' => 'Yok' ,
   'LBL_ALLOW_OWNER' => 'Sahibi' ,
   'LBL_ROLE' => 'Rol' ,
   'LBL_NAME' => 'İsim' ,
   'LBL_DESCRIPTION' => 'Tanım' ,
   'LIST_ROLES' => 'Roller Listesi' ,
   'LBL_USERS_SUBPANEL_TITLE' => 'Kullanıcılar' ,
   'LIST_ROLES_BY_USER' => 'Rolleri Kullanıcılara Göre Listele' ,
   'LBL_ROLES_SUBPANEL_TITLE' => 'Kullanıcı Rolleri' ,
   'LBL_SEARCH_FORM_TITLE' => 'Ara' ,
   'LBL_NO_ACCESS' => 'Bu bölüme erişim izniniz yok. İzin için lütfen site yöneticiniz ile temasa geçin.' ,
   'LBL_REDIRECT_TO_HOME' => 'Ana Sayfaya Yönlendirme süresi' ,
   'LBL_SECONDS' => 'saniye' ,
   'LBL_ADDING' => 'Ekleme yapılıyor:' );

?>
