<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/History/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Tarihçe' ,
   'LBL_MODULE_TITLE' => 'Tarihçe: Ana Sayfa' ,
   'LBL_SEARCH_FORM_TITLE' => 'Tarihçe Arama' ,
   'LBL_LIST_FORM_TITLE' => 'Tarihçe' ,
   'LBL_LIST_SUBJECT' => 'Konu' ,
   'LBL_LIST_CONTACT' => 'Kontak' ,
   'LBL_LIST_RELATED_TO' => 'İlişkili' ,
   'LBL_LIST_DATE' => 'Tarih' ,
   'LBL_LIST_TIME' => 'Başlangıç Saati' ,
   'LBL_LIST_CLOSE' => 'Kapat' ,
   'LBL_SUBJECT' => 'Not Konusu:' ,
   'LBL_STATUS' => 'Durum:' ,
   'LBL_LOCATION' => 'Yer:' ,
   'LBL_DATE_TIME' => 'Başlangıç Tarih & Saati:' ,
   'LBL_DATE' => 'Başlangıç Tarihi:' ,
   'LBL_TIME' => 'Başlangıç Saati:' ,
   'LBL_DURATION' => 'Süre:' ,
   'LBL_HOURS_MINS' => '(saat/dakika)' ,
   'LBL_CONTACT_NAME' => 'Kontak İsmi:' ,
   'LBL_MEETING' => 'Toplantı:' ,
   'LBL_DESCRIPTION_INFORMATION' => 'Tanım Bilgisi' ,
   'LBL_DESCRIPTION' => 'Tanım:' ,
   'LBL_COLON' => ':' ,
   'LBL_DEFAULT_STATUS' => 'Planlanmış' ,
   'LNK_NEW_CALL' => 'Tel. Araması Planla' ,
   'LNK_NEW_MEETING' => 'Toplantı Planla' ,
   'LNK_NEW_TASK' => 'Görev Oluştur' ,
   'LNK_NEW_NOTE' => 'Not veya Ek Oluştur' ,
   'LNK_NEW_EMAIL' => 'E-Posta Arşivle' ,
   'LNK_CALL_LIST' => 'Çağrılar' ,
   'LNK_MEETING_LIST' => 'Toplantılar' ,
   'LNK_TASK_LIST' => 'Görevler' ,
   'LNK_NOTE_LIST' => 'Notlar' ,
   'LNK_EMAIL_LIST' => 'E-Postalar' ,
   'ERR_DELETE_RECORD' => 'Müşteriyi silmek için bir kayıt numarası belirtilmelidir.' ,
   'NTC_REMOVE_INVITEE' => 'Toplantıdan bu davetliyi kaldırmak istediğinizden emin misiniz?' ,
   'LBL_INVITEE' => 'Davetliler' ,
   'LBL_LIST_DIRECTION' => 'Yön' ,
   'LBL_DIRECTION' => 'Yön' ,
   'LNK_NEW_APPOINTMENT' => 'Yeni Randevu' ,
   'LNK_VIEW_CALENDAR' => 'Bugün' ,
   'LBL_OPEN_ACTIVITIES' => 'Aktiviteleri Aç' ,
   'LBL_HISTORY' => 'Tarihçe' ,
   'LBL_UPCOMING' => 'Yaklaşan Randevularım' ,
   'LBL_TODAY' => 'boyunca' ,
   'LBL_NEW_TASK_BUTTON_TITLE' => 'Görev Oluştur' ,
   'LBL_NEW_TASK_BUTTON_KEY' => 'N' ,
   'LBL_NEW_TASK_BUTTON_LABEL' => 'Görev Oluştur' ,
   'LBL_SCHEDULE_MEETING_BUTTON_TITLE' => 'Toplantı Planla' ,
   'LBL_SCHEDULE_MEETING_BUTTON_KEY' => 'M' ,
   'LBL_SCHEDULE_MEETING_BUTTON_LABEL' => 'Toplantı Planla' ,
   'LBL_SCHEDULE_CALL_BUTTON_TITLE' => 'Tel. Araması Planla' ,
   'LBL_SCHEDULE_CALL_BUTTON_KEY' => 'C' ,
   'LBL_SCHEDULE_CALL_BUTTON_LABEL' => 'Tel. Araması Planla' ,
   'LBL_NEW_NOTE_BUTTON_TITLE' => 'Not veya Ek Oluştur' ,
   'LBL_NEW_NOTE_BUTTON_KEY' => 'T' ,
   'LBL_NEW_NOTE_BUTTON_LABEL' => 'Not veya Ek Oluştur' ,
   'LBL_TRACK_EMAIL_BUTTON_TITLE' => 'E-Posta Arşivle' ,
   'LBL_TRACK_EMAIL_BUTTON_KEY' => 'Bin' ,
   'LBL_TRACK_EMAIL_BUTTON_LABEL' => 'E-Posta Arşivle' ,
   'LBL_LIST_STATUS' => 'Durum' ,
   'LBL_LIST_DUE_DATE' => 'Son Bitirme Tarihi' ,
   'LBL_LIST_LAST_MODIFIED' => 'Değiştirilme Tarihi' ,
   'NTC_NONE_SCHEDULED' => 'Hiç planlanmamış.' ,
   'LNK_IMPORT_NOTES' => 'Not Verilerini Yükle' ,
   'NTC_NONE' => 'Yok' ,
   'LBL_ACCEPT_THIS' => 'Kabul?' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'Tarihçe' ,
   'appointment_filter_dom' => array (
      'today' => 'bugün' ,
      'tomorrow' => 'yarın' ,
      'this Saturday' => 'bu hafta' ,
      'next Saturday' => 'sonraki hafta' ,
      'last this_month' => 'bu ay' ,
      'last next_month' => 'sonraki ay'   ));

?>
