<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Connectors/connectors/sources/ext/rest/zoominfocompany/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$connector_strings = array ( 
   'LBL_LICENSING_INFO' => '<table border="0" cellspacing="1"><tr><td valign="top" width="35%" class="dataLabel"><image src="MANUAL CHANGE ADVOCOTEK" border="0"></td><td width="65%" valign="top" class="dataLabel">ZoomInfo&#169; 5 milyon şirkette çalışan 45 milyon profesyonel hakkında detaylı bilgi sağlar. Daha fazlası için  <a target="_blank" href="http://www.zoominfo.com/about">http://www.zoominfo.com/about</a></td></tr></table>' ,
   'LBL_SEARCH_FIELDS_INFO' => 'Şu alanlar Zoominfo&#169 tarafından desteklenmektedir. Şirket; API: Şirket İsmi, Şehir, Eyalet ve Posta Kodu.' ,
   'LBL_COMPANY_ID' => 'ID' ,
   'LBL_COMPANY_NAME' => 'Şirket İsmi' ,
   'LBL_STREET' => 'Sokak' ,
   'LBL_CITY' => 'Şehir' ,
   'LBL_ZIP' => 'Posta Kodu' ,
   'LBL_STATE' => 'Eyalet' ,
   'LBL_COUNTRY' => 'Ülke' ,
   'LBL_INDUSTRY' => 'Endüstri' ,
   'LBL_WEBSITE' => 'Web Sitesi' ,
   'LBL_DESCRIPTION' => 'Tanım' ,
   'LBL_PHONE' => 'Telefon' ,
   'LBL_COMPANY_TICKER' => 'Şirket Sayacı' ,
   'LBL_ZOOMINFO_COMPANY_URL' => 'Şirket Profili URL' ,
   'LBL_REVENUE' => 'Yıllık Gelir' ,
   'LBL_EMPLOYEES' => 'Çalışanlar' ,
   'company_search_url' => 'Şirket Arama URL' ,
   'company_detail_url' => 'Şirket Detay URL' ,
   'partner_code' => 'Partner API Kod' ,
   'api_key' => 'API ANAHTARI' ,
   'ERROR_LBL_CONNECTION_PROBLEM' => 'Hata: Zoominfo - Şirket bağlantısı için sunucuya bağlanılamıyor.' );

?>
