<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Contracts/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Kontratlar' ,
   'LBL_MODULE_TITLE' => 'Kontratlar : Ana Sayfa' ,
   'LNK_NEW_CONTRACT' => 'Kontrat Oluştur' ,
   'LNK_CONTRACT_LIST' => 'Kontratları Görüntüle' ,
   'LBL_NEW_FORM_TITLE' => 'Yeni Kontrat' ,
   'LBL_CONTRACT_NAME' => 'Kontrat İsmi:' ,
   'LBL_REFERENCE_CODE' => 'Referans Kodu:' ,
   'LBL_ACCOUNT_NAME' => 'Müşteri İsmi:' ,
   'LBL_OPPORTUNITY' => 'Fırsat' ,
   'LBL_START_DATE' => 'Başlangıç Tarihi:' ,
   'LBL_END_DATE' => 'Bitiş Tarihi:' ,
   'LBL_TOTAL_CONTRACT_VALUE' => 'Kontrat Değeri:' ,
   'LBL_TOTAL_CONTRACT_VALUE_USDOLLAR' => 'Kontrat Değeri (USD):' ,
   'LBL_STATUS' => 'Durum:' ,
   'LBL_CUSTOMER_SIGNED_DATE' => 'Müşterinin İmzaladığı Tarih:' ,
   'LBL_COMPANY_SIGNED_DATE' => 'Şirketin İmzaladığı Tarih:' ,
   'LBL_CONTRACT_TERM' => 'Kontrat Koşulları:' ,
   'LBL_EXPIRATION_NOTICE' => 'Sona Erme Bildirimi:' ,
   'LBL_TIME_TO_EXPIRY' => 'Bitiş Tarihi:' ,
   'LBL_DESCRIPTION' => 'Tanım:' ,
   'LBL_TEAM' => 'Takım:' ,
   'LBL_ASSIGNED_TO' => 'Atanan Kişi:' ,
   'LBL_CURRENCY_ID' => 'Para Birimi ID:' ,
   'LBL_CURRENCY' => 'Para Birimi:' ,
   'LBL_ASSIGNED_TO_NAME' => 'Atanan Kişi:' ,
   'LBL_LIST_FORM_TITLE' => 'Kontrat Listesi' ,
   'LBL_LIST_CONTRACT_NAME' => 'Kontrat İsmi' ,
   'LBL_LIST_ACCOUNT_NAME' => 'Müşteri İsmi' ,
   'LBL_LIST_START_DATE' => 'İlk' ,
   'LBL_LIST_END_DATE' => 'Son' ,
   'LBL_LIST_STATUS' => 'Durum' ,
   'LBL_LIST_TEAM_NAME' => 'Takım' ,
   'LBL_LIST_ASSIGNED_TO_USER' => 'Kullanıcı' ,
   'LBL_DAYS' => 'Gün(ler)' ,
   'LBL_UNDEFINED' => 'Tanımlanmamış' ,
   'LBL_NONE' => 'Yok' ,
   'LBL_SEARCH_FORM_TITLE' => 'Kontrat Arama' ,
   'LBL_SF_CONTRACT_NAME' => 'Kontrat İsmi:' ,
   'LBL_SF_ACCOUNT_NAME' => 'Müşteri İsmi:' ,
   'LBL_SF_STATUS' => 'Durum:' ,
   'LBL_SF_CONTRACT_TYPE' => 'Tipi:' ,
   'LBL_SF_START_DATE' => 'Başlangıç Tarihi:' ,
   'LBL_SF_END_DATE' => 'Bitiş Tarihi:' ,
   'LBL_SF_ASSIGNED_TO' => 'Atanan Kişi:' ,
   'LBL_DOCUMENTS_SUBPANEL_TITLE' => 'Dokümanlar' ,
   'LBL_CONTACTS_SUBPANEL_TITLE' => 'Kontaklar' ,
   'LBL_NOTES_SUBPANEL_TITLE' => 'Notlar' ,
   'LBL_PRODUCTS_SUBPANEL_TITLE' => 'Ürünler' ,
   'LBL_QUOTES_SUBPANEL_TITLE' => 'Teklifler' ,
   'LBL_LIST_NAME' => 'İsim' ,
   'LBL_LIST_CONTRACT_VALUE' => 'Değer' ,
   'LBL_TYPE' => 'Tipi' ,
   'LBL_CONTRACT_TYPE' => 'Tipi:' ,
   'LBL_CREATED_USER' => 'Oluşturan Kullanıcı' ,
   'LBL_MODIFIED_USER' => 'Değiştiren Kullanıcı' ,
   'LBL_DOCUMENTS' => 'Dokümanlar' ,
   'LBL_CONTRACT_DOCUMENTS_SUBPANEL_TITLE' => 'Dokümanlar' ,
   'LBL_CONTRACT_INFORMATION' => 'Genel Bakış' );

?>
