<?php $V65390101 = array( 'CE' => array( 'rls_Candidates' => 'rls_Candidates', 'rls_Employment' => 'rls_Employment',
 'rls_Applications' => 'rls_Applications', 'candidate_field' => array( 'full_name' => 'last_name',
 'memberId' => 'linkedin_account', 'locality' => 'primary_address_street', 'industry' => 'description',
 'email' => 'email1', ), 'employment_field' => array( 'current' => 'rls_current', ), 'applications_field' => array(
 'candidate_id' => 'rls_candidce11didates_ida', 'job_id' => 'rls_jobs_r40c0ls_jobs_ida', ), 'notes_relationship' => array(
 'rls_Candidates' => 'rls_candidates_activities_notes', 'Contacts' => 'notes', 'Accounts' => 'notes',
 'Leads' => 'notes', ), 'mapping_for_standart_modules' => array( 'rls_Candidates' => array( 'full_name' => 'last_name',
 'memberId' => 'linkedin_account', 'memberId2' => 'linkedin_account2', 'locality' => 'primary_address_street',
 'industry' => 'can_industry_c', 'email' => 'email1', 'description' => 'description', 'linkedin_url' => 'linkedin_profile',
 'reccord_status_val' => 'main_status', 'phone' => 'phone_mobile', 'current_workplace' => 'current_employer',
 'headline' => 'last_position', ), 'Contacts' => array( 'full_name' => 'last_name', 'memberId' => 'rls_linkedin_account_c',
 'memberId2' => 'rls_linkedin_account2_c', 'locality' => 'primary_address_street', 'industry' => 'rls_industry_c',
 'email' => 'email1', 'description' => 'description', 'linkedin_url' => 'rls_linkedin_url_c', 'current_workplace' => 'rls_current_workplace_c',
 'headline' => 'rls_last_position_c', 'phone' => 'phone_mobile', 'account_id' => 'account_id', 'account_name' => 'account_name',
 ), 'Accounts' => array( 'full_name' => 'name', 'memberId' => 'rls_linkedin_account_c', 'memberId2' => 'rls_linkedin_account2_c',
 'locality' => 'billing_address_street', 'industry' => 'rls_industry_c', 'email' => 'email1', 'description' => 'description',
 'linkedin_url' => 'rls_linkedin_url_c', 'current_workplace' => 'rls_current_workplace_c', 'headline' => 'rls_last_position_c',
 'phone' => 'phone_office', ), 'Leads' => array( 'full_name' => 'last_name', 'memberId' => 'rls_linkedin_account_c',
 'memberId2' => 'rls_linkedin_account2_c', 'locality' => 'primary_address_street', 'industry' => 'rls_industry_c',
 'email' => 'email1', 'description' => 'description', 'linkedin_url' => 'rls_linkedin_url_c', 'current_workplace' => 'rls_current_workplace_c',
 'headline' => 'rls_last_position_c', 'reccord_status_val' => 'status', 'phone' => 'phone_mobile',
 ), 'Prospects' => array( 'full_name' => 'last_name', 'memberId' => 'rls_linkedin_account_c', 'memberId2' => 'rls_linkedin_account2_c',
 'locality' => 'primary_address_street', 'industry' => 'rls_industry_c', 'email' => 'email1', 'description' => 'description',
 'linkedin_url' => 'rls_linkedin_url_c', 'current_workplace' => 'rls_current_workplace_c', 'headline' => 'rls_last_position_c',
 'phone' => 'phone_mobile', ), ), ), 'PRO' => array( 'rls_Candidates' => 'RLS_Candidates', 'rls_Employment' => 'RLS_Employment',
 'rls_Applications' => 'RLS_Applications', 'candidate_field' => array( 'full_name' => 'last_name',
 'memberId' => 'linkedin_account', 'locality' => 'primary_address_street', 'industry' => 'reffered_description',
 'email' => 'email1', ), 'employment_field' => array( 'current' => 'current_', ), 'applications_field' => array(
 'candidate_id' => 'rls_applications_rls_candidatesrls_candidates_ida', 'job_id' => 'rls_applications_rls_jobsrls_jobs_ida',
 ), 'notes_relationship' => array( 'rls_Candidates' => 'rls_candidates_activities_1_notes', 'Contacts' => 'notes',
 'Accounts' => 'notes', 'Leads' => 'notes', ), 'mapping_for_standart_modules' => array( 'rls_Candidates' => array(
 'full_name' => 'last_name', 'memberId' => 'linkedin_account', 'memberId2' => 'linkedin_account2',
 'current_position' => 'current_position', 'primary_address_street' => 'primary_address_street', 'current_employer' => 'current_employer',
 'industry' => 'current_industry', 'locality' => 'primary_address_street', 'email' => 'email1', 'description' => 'reffered_description',
 'linkedin_url' => 'linkedin_url', 'reccord_status_val' => 'main_status', 'phone' => 'phone_mobile',
 ), 'Contacts' => array( 'full_name' => 'last_name', 'memberId' => 'rls_linkedin_account_c', 'memberId2' => 'rls_linkedin_account2_c',
 'locality' => 'primary_address_street', 'industry' => 'rls_industry_c', 'email' => 'email1', 'description' => 'description',
 'linkedin_url' => 'rls_linkedin_url_c', 'current_workplace' => 'rls_current_workplace_c', 'headline' => 'rls_last_position_c',
 'phone' => 'phone_mobile', 'account_id' => 'account_id', 'account_name' => 'account_name', ), 'Accounts' => array(
 'full_name' => 'name', 'memberId' => 'rls_linkedin_account_c', 'memberId2' => 'rls_linkedin_account2_c',
 'locality' => 'billing_address_street', 'industry' => 'rls_industry_c', 'email' => 'email1', 'description' => 'description',
 'linkedin_url' => 'rls_linkedin_url_c', 'current_workplace' => 'rls_current_workplace_c', 'headline' => 'rls_last_position_c',
 'phone' => 'phone_office', ), 'Leads' => array( 'full_name' => 'last_name', 'memberId' => 'rls_linkedin_account_c',
 'memberId2' => 'rls_linkedin_account2_c', 'locality' => 'primary_address_street', 'industry' => 'rls_industry_c',
 'email' => 'email1', 'description' => 'description', 'linkedin_url' => 'rls_linkedin_url_c', 'current_workplace' => 'rls_current_workplace_c',
 'headline' => 'rls_last_position_c', 'reccord_status_val' => 'status', 'phone' => 'phone_mobile',
 ), 'Prospects' => array( 'full_name' => 'last_name', 'memberId' => 'rls_linkedin_account_c', 'memberId2' => 'rls_linkedin_account2_c',
 'locality' => 'primary_address_street', 'industry' => 'rls_industry_c', 'email' => 'email1', 'description' => 'description',
 'linkedin_url' => 'rls_linkedin_url_c', 'current_workplace' => 'rls_current_workplace_c', 'headline' => 'rls_last_position_c',
 'phone' => 'phone_mobile', ), ), ), ); 