<?php


$dictionary['SYNO_DashboardTemplateLines'] = array(
    'table' => 'syno_dashboardtemplatelines',
    'audited' => true,
    'activity_enabled' => false,
        'duplicate_merge' => true,
        'fields' => array(

'template_dashboard_type' => array(
    'required' => false,
    'name' => 'template_dashboard_type',
    'vname' => 'LBL_TEMPLATE_DASHBOARD_TYPE',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'false',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => array(
      'boost' => '0',
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'template_name' => array(
    'required' => false,
    'name' => 'template_name',
    'vname' => 'LBL_TEMPLATE_NAME',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'false',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => array(
      'boost' => '0',
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'template_dashboard_module' => array(
    'required' => false,
    'name' => 'template_dashboard_module',
    'vname' => 'LBL_TEMPLATE_DASHBOARD_MODULE',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'false',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => array(
      'boost' => '0',
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'template_view' => array(
    'required' => false,
    'name' => 'template_view',
    'vname' => 'LBL_TEMPLATE_VIEW',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => array(
      'boost' => '0',
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'template_metadata' => array(
    'required' => false,
    'name' => 'template_metadata',
    'vname' => 'LBL_TEMPLATE_METADATA',
    'type' => 'text',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'false',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => array(
      'boost' => '0',
    ),
    'calculated' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
),
    'relationships' => array(
),
    'acls' => array(
        'SugarACLAdminOnly' => true,
    ),
    'optimistic_locking' => true,
        'unified_search' => true,
    );
if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('SYNO_DashboardTemplateLines', 'SYNO_DashboardTemplateLines', array('basic', 'assignable'));
