<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Connectors/connectors/sources/ext/rest/zoominfoperson/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$connector_strings = array ( 
   'LBL_LICENSING_INFO' => '<table border="0" cellspacing="1"><tr><td valign="top" width="35%" class="dataLabel"><image src="MANUAL CHANGE ADVOCOTEK" border="0"></td><td width="65%" valign="top" class="dataLabel">ZoomInfo&#169; 5 milyon şirkette çalışan 45 milyon profesyonel hakkında detaylı bilgi sağlar. Daha fazlası için  <a target="_blank" href="http://www.zoominfo.com/about">http://www.zoominfo.com/about</a></td></tr></table>' ,
   'LBL_SEARCH_FIELDS_INFO' => 'Şu alanlar Zoominfo&#169 tarafından desteklenmektedir. Kişi; API: İlk İsmi, Soyadı ve E-Posta adresi.' ,
   'LBL_ID' => 'ID' ,
   'LBL_EMAIL' => 'E-Posta Adresi' ,
   'LBL_FIRST_NAME' => 'İsim' ,
   'LBL_LAST_NAME' => 'Soyisim' ,
   'LBL_JOB_TITLE' => 'İş Unvanı' ,
   'LBL_IMAGE_URL' => 'Resim URL si' ,
   'LBL_SUMMARY_URL' => 'Özet URL si' ,
   'LBL_COMPANY_NAME' => 'Şirket İsmi' ,
   'LBL_ZOOMPERSON_URL' => 'Zoominfo Kişi URL' ,
   'LBL_DIRECT_PHONE' => 'Ana Telefon' ,
   'LBL_COMPANY_PHONE' => 'Şirket Telefonu' ,
   'LBL_FAX' => 'Faks' ,
   'LBL_CURRENT_JOB_TITLE' => 'Mevcut İş Unvanı' ,
   'LBL_CURRENT_JOB_START_DATE' => 'Mevcut İş Başlama Tarihi' ,
   'LBL_CURRENT_JOB_COMPANY_NAME' => 'Mevcut İş Şirket İsmi' ,
   'LBL_CURRENT_JOB_COMPANY_STREET' => 'Mevcut İş Sokak Adresi' ,
   'LBL_CURRENT_JOB_COMPANY_CITY' => 'Mevcut İş Şehir Adresi' ,
   'LBL_CURRENT_JOB_COMPANY_STATE' => 'Mevcut İş Bölge Adresi' ,
   'LBL_CURRENT_JOB_COMPANY_ZIP' => 'Mevcut İş Posta Kodu' ,
   'LBL_CURRENT_JOB_COMPANY_COUNTRY_CODE' => 'Mevcut İş Ülke Kodu' ,
   'LBL_CURRENT_INDUSTRY' => 'Mevcut İş Endüstri' ,
   'LBL_BIOGRAPHY' => 'Biyografi' ,
   'LBL_EDUCATION_SCHOOL' => 'Kolej/Üniversite' ,
   'LBL_AFFILIATION_TITLE' => 'İlişkili İş Unvanı' ,
   'LBL_AFFILIATION_COMPANY_PHONE' => 'İlişkili Şirket Telefonu' ,
   'LBL_AFFILIATION_COMPANY_NAME' => 'İlişkili Şirket İsmi' ,
   'LBL_AFFILIATION_COMPANY_WEBSITE' => 'İlişkili Şirket Web sitesi' ,
   'person_search_url' => 'Kişi Arama Sorgu URL si' ,
   'person_detail_url' => 'Kişi Detay Sorgu URL si' ,
   'partner_code' => 'Partner API Kod' ,
   'api_key' => 'API Anahtar' ,
   'ERROR_LBL_CONNECTION_PROBLEM' => 'Hata: Zoominfo - Şirket bağlantısı için sunucuya bağlanılamıyor.' );

?>
