<?PHP

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN SYNO_DashboardTemplates
 */

class SYNO_DashboardTemplates_sugar extends Basic
{
    public $new_schema = true;
    public $module_dir = 'SYNO_DashboardTemplates';
    public $object_name = 'SYNO_DashboardTemplates';
    public $table_name = 'syno_dashboardtemplates';
    public $importable = false;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $template_data;
    public $flag_data;
    public $disable_row_level_security = true;

    /**
     * This is a depreciated method, please start using __construct() as this method will be removed in a future version
     *
     * @see __construct
     * @depreciated
     */
    public function SYNO_DashboardTemplates_sugar()
    {
        self::__construct();
    }

    public function __construct()
    {
        parent::__construct();
    }

    public function bean_implements($interface)
    {
        switch ($interface) {
            case 'ACL': return true;
        }

        return false;
    }
}
