<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Currencies/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Para Birimleri' ,
   'LBL_LIST_FORM_TITLE' => 'Para Birimleri' ,
   'LBL_CURRENCY' => 'Para Birimi' ,
   'LBL_ADD' => 'Ekle' ,
   'LBL_MERGE' => 'Birleştir' ,
   'LBL_MERGE_TXT' => 'Lütfen seçilen para birimine eşleştirmek istediğiniz para birimlerini seçiniz. Bu işlem, işaretli tüm para birimlerini silecek ve ilgili tüm değerleri seçilen yeni para birimine atayacaktır.' ,
   'LBL_US_DOLLAR' => 'ABD Doları' ,
   'LBL_DELETE' => 'Sil' ,
   'LBL_LIST_SYMBOL' => 'Para Birimi Sembolü' ,
   'LBL_LIST_NAME' => 'Para Birimi İsmi' ,
   'LBL_LIST_ISO4217' => 'ISO 4217 Kodu' ,
   'LBL_LIST_ISO4217_HELP' => 'Para birimini ve para sembolünü belirten 3 harfli bir ISO 4217 kodu girin.' ,
   'LBL_UPDATE' => 'Güncelle' ,
   'LBL_LIST_RATE' => 'Dönüştürme Oranı' ,
   'LBL_LIST_RATE_HELP' => 'Euro için dönüştürme oranı 0.5 ise, 10 USD= 5 Euro demektir.' ,
   'LBL_LIST_STATUS' => 'Durum' ,
   'LNK_NEW_CONTACT' => 'Yeni Kontak' ,
   'LNK_NEW_ACCOUNT' => 'Yeni Müşteri' ,
   'LNK_NEW_OPPORTUNITY' => 'Yeni Fırsat' ,
   'LNK_NEW_CASE' => 'Yeni Talep' ,
   'LNK_NEW_NOTE' => 'Not veya Ek Oluştur' ,
   'LNK_NEW_CALL' => 'Yeni Tel. Arama' ,
   'LNK_NEW_EMAIL' => 'Yeni E-Posta' ,
   'LNK_NEW_MEETING' => 'Yeni Toplantı' ,
   'LNK_NEW_TASK' => 'Görev Oluştur' ,
   'NTC_DELETE_CONFIRMATION' => 'Bu kaydı silmek istediğinize emin misiniz? Bu para birimini kullanan kayıtlara ulaşıldığında, sistem varsayılan para birimini kullanacaktır. Durumu İnaktif olarak işaretlemek daha doğru olabilir.' ,
   'LBL_BELOW_MIN' => 'Dönüşüm oranı 0 dan fazla olmalı' ,
   'LBL_CREATED_BY' => 'Oluşturan' ,
   'LBL_EDIT_LAYOUT' => 'Yerleşimi Değiştir' ,
   'currency_status_dom' => array (
      'Active' => 'Aktif' ,
      'Inactive' => 'İnaktif'   ));

?>
