<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Releases/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Sürümler' ,
   'LBL_MODULE_TITLE' => 'Sürümler: Ana Sayfa' ,
   'LBL_SEARCH_FORM_TITLE' => 'Sürüm Arama' ,
   'LBL_LIST_FORM_TITLE' => 'Sürüm Listesi' ,
   'LBL_NEW_FORM_TITLE' => 'Yeni Sürüm' ,
   'LBL_RELEASE' => 'Sürüm:' ,
   'LBL_LIST_NAME' => 'Sürüm' ,
   'LBL_NAME' => 'Sürüm:' ,
   'LBL_LIST_LIST_ORDER' => 'Sıra' ,
   'LBL_LIST_ORDER' => 'Sıra:' ,
   'LBL_LIST_STATUS' => 'Durum' ,
   'LBL_STATUS' => 'Durum:' ,
   'LNK_NEW_RELEASE' => 'Sürüm Listesi' ,
   'NTC_DELETE_CONFIRMATION' => 'Bu kaydı silmek istediğinizden emin misiniz?' ,
   'ERR_DELETE_RECORD' => 'Sürümü silmek için kayıt numarasını belirtmeniz gerekmektedir.' ,
   'NTC_STATUS' => 'Bu sürümün durumunu, İnaktif olarak belirleyerek Sürüm açılır-listesinden kaldırın' ,
   'NTC_LIST_ORDER' => 'Bu sürümün, Sürüm açılır-listesinde görünmesini istediğiniz sırayı belirleyin' ,
   'LBL_EDITLAYOUT' => 'Yerleşimi Değiştir' ,
   'release_status_dom' => array (
      'Active' => 'Aktif' ,
      'Inactive' => 'İnaktif'   ));

?>
