<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/TeamNotices/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Takım Bildirimleri' ,
   'LBL_MODULE_TITLE' => 'Takım Bildirimleri: Ana Sayfa' ,
   'LBL_SEARCH_FORM_TITLE' => 'Takım Bildirim Arama' ,
   'LBL_LIST_FORM_TITLE' => 'Takım Bildirim Listesi' ,
   'LBL_PRODUCTTYPE' => 'Takım Bildirimi' ,
   'LBL_NOTICES' => 'Takım Bildirimleri' ,
   'LBL_LIST_NAME' => 'Başlık' ,
   'LBL_URL' => 'URL' ,
   'LBL_URL_TITLE' => 'URL Başlığı' ,
   'LBL_LIST_DESCRIPTION' => 'Tanım' ,
   'LBL_NAME' => 'Başlık' ,
   'LBL_DESCRIPTION' => 'Tanım' ,
   'LBL_LIST_LIST_ORDER' => 'Sıra' ,
   'LBL_LIST_ORDER' => 'Sıra' ,
   'LBL_DATE_START' => 'Başlama Tarihi' ,
   'LBL_DATE_END' => 'Bitiş Tarihi' ,
   'LBL_STATUS' => 'Durum' ,
   'LNK_NEW_TEAM' => 'Takım Oluştur' ,
   'LNK_NEW_TEAM_NOTICE' => 'Takım Bildirimi Oluştur' ,
   'LNK_LIST_TEAM' => 'Takımlar' ,
   'LNK_LIST_TEAMNOTICE' => 'Takım Bildirimleri' ,
   'LNK_PRODUCT_LIST' => 'Ürün Fiyat Listesi' ,
   'LNK_NEW_PRODUCT' => 'Ürün Oluştur' ,
   'LNK_NEW_MANUFACTURER' => 'Üreticiler' ,
   'LNK_NEW_SHIPPER' => 'Nakliyat Sağlayıcıları' ,
   'LNK_NEW_PRODUCT_CATEGORY' => 'Ürün Kategorileri' ,
   'LNK_NEW_PRODUCT_TYPE' => 'Ürün Çeşit Listesi' ,
   'NTC_DELETE_CONFIRMATION' => 'Bu kaydı silmek istediğinizden emin misiniz?' ,
   'ERR_DELETE_RECORD' => 'Ürün tipini silmek için kayıt numarasını belirtmeniz gerekmektedir.' ,
   'NTC_LIST_ORDER' => 'Bu ürün tipinin, Ürün Tipi açılır-liste sinde görünmesini istediğiniz sırayı belirleyin' ,
   'LBL_TEAM_NOTICE_FEATURES' => 'Özellikler: 
* Gelişmiş Kullanıcı ara yüzü ve Sihirbaz sayesinde, Rapor oluşturmak çok daha kolay ve gelişmiş özelliklere sahip.
* Komplike Raporlama Kümeleri sayesinde kullanıcılar modüller arası çok fazla detay içeren raporlar hazırlayabiliyor. 
* Matris Raporları sayesinde birçok özelliği esnek bir görünümde gruplayabilirsiniz. Pivot tabloları oluşturarak, Toplama, Ortalama, Sayı ve Yüzde gibi fonksiyonlar kullanılabilir. 
*Çalışma Sırasındaki Filtreler, kullanıcıların gerçek zamanda özelliklerde değişiklik yapabilmelerine izin verir.' ,
   'LBL_TEAM_NOTICE_WIRELESS' => 'SugarCRM uygulamasının yeni mobil görünümü kullanışlılık ve taşınabilirlik arasında tercih etme zorunluluğunu ortadan kaldırır. Özellikleri:
* Geliştirilmiş kullanıcı ara yüzü sayesinde değiştirme, detay, liste görünümleri ve ilişkili kayıtlar görüntülenebilir, hatta personel klasörlerine, mağaza tercihleri,  ve son öğeler de görüntülenebilir. 
* Cihaz Bağımsızlığı, kullanıcının SugarCRM verilerine herhangi bir PDA yada akıllı telefon (IPhone ve Blackberry dahil) aracılığı ile ulaşmasını sağlar. 
* Zengin HTML İstemcisi, standart bir web tarayıcısı üzerinden SugarCRM verilerin temiz sunumu sağlar. 
* Yeni Arama Yetenekler kullanıcılar bilgileri hızlı bir şekilde bulmasını sağlar.' ,
   'LBL_TEAM_NOTICE_DATA_IMPORT' => 'Veri Yükleme Yenilikleri ile artık Excel, Act!, MS Outlook ve Salesforce.com gibi uygulamalardan SugarCRM e veri aktarımı çok daha kolay. Yenilikler: 
* Geliştirilmiş Ara yüz, kullanıcılara veri eşlemelerinde büyük kolaylıklar oluşturuyor ve verinin doğru bir biçimde aktarılmasını sağlar. 
* Veri Kalite Kontrolü sayesinde, sistem yöneticileri, tekrar eden bilgileri azaltarak aktarılan verilerden yeni kayıtlar oluşturması, veya var olan kayıtları güncellenmesini sağlayarak, veri kirliliği engellenebilir. Tüm Modüllere aktarma sayesinde diğer CRM uygulamalarından herhangi bir modüle veri aktarımı yapılabilir, böylece tekrar eden veri girişi engellenmiş olur.' ,
   'LBL_TEAM_NOTICE_MODULE_BUILDER' => 'Modül Oluşturucu sayesinde mevcut SugarCRM modüllerinize oluşturucu yeni modüller ekleyebilirsiniz. Yenilikler:  
* Yeni İlişkiler sayesinde, yeni ve eski modüller arasında farklı şekillerde ilişkiler kurulabilir.  
* Denetlemeler sayesinde modül oluşturma ve değişikliklerin tarihçesi tutulur ve böylece yapılan değişiklikler takip edilebilir.  
* Dashlet Destekleri sayesinde özel nesne ve modül işlevselliklerinin AJAX ile görüntülenmesine olanak sağlar.  
* Yeni Şablonlar sayesinde dosyalar ve yeni fırsat bilgileri kolaylıkla takip edilebilir.' ,
   'LBL_TEAM_NOTICE_TRACKER' => 'Takipçi sayesinde SugarCRM in kullanım ve performansı hakkında geniş bir bilgiye erişilebilir. Yenilikler: * Takipçi Raporlar sistem kullanımı içine anlık görüntüler sağlayarak, kullanıcı adaptasyonunu ve CRM&#39;den faydalanmak için görünürlüğü arttırır. Kullanıcılar haftalık raporlar alarak, aktiviteleri, kayıtları, görüntülenen modülleri, kümülatif sistemde geçirdikleri süre ve diğer takım arkadaşlarının bilgilerine ulaşabilirler. * Sistem monitörleri sayesinde Sistem Yöneticileri uygulamanın nasıl kullanıldığını ve farklı stres noktalarını belirleyebilirler.' ,
   'LBL_MORE_DETAIL' => 'Daha Fazla Detay' ,
   'dom_status' => array (
      'Visible' => 'Görünür' ,
      'Hidden' => 'Gizli'   ));

?>
