<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/DynamicFields/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LNK_NEW_CALL' => 'Tel. Araması Planla' ,
   'LNK_NEW_MEETING' => 'Toplantı Planla' ,
   'LNK_NEW_TASK' => 'Görev Oluştur' ,
   'LNK_NEW_NOTE' => 'Not veya Ek Oluştur' ,
   'LNK_NEW_EMAIL' => 'E-Posta Arşivle' ,
   'LNK_CALL_LIST' => 'Çağrılar' ,
   'LNK_MEETING_LIST' => 'Toplantılar' ,
   'LNK_TASK_LIST' => 'Görevler' ,
   'LNK_NOTE_LIST' => 'Notlar' ,
   'LNK_EMAIL_LIST' => 'E-Postalar' ,
   'LBL_ADD_FIELD' => 'Alan Ekle:' ,
   'LBL_MODULE_SELECT' => 'Değiştirilecek Modül' ,
   'LBL_SEARCH_FORM_TITLE' => 'Modül Arama' ,
   'COLUMN_TITLE_NAME' => 'Alan İsmi' ,
   'COLUMN_TITLE_DISPLAY_LABEL' => 'Etiketi Görüntüle' ,
   'COLUMN_TITLE_LABEL_VALUE' => 'Etiket Değeri' ,
   'COLUMN_TITLE_LABEL' => 'Sistem Etiketi' ,
   'COLUMN_TITLE_DATA_TYPE' => 'Veri Tipi' ,
   'COLUMN_TITLE_MAX_SIZE' => 'Maksimum Boyut' ,
   'COLUMN_TITLE_HELP_TEXT' => 'Yardım Metni' ,
   'COLUMN_TITLE_COMMENT_TEXT' => 'Yorum Metni' ,
   'COLUMN_TITLE_REQUIRED_OPTION' => 'Gereken Alan' ,
   'COLUMN_TITLE_DEFAULT_VALUE' => 'Varsayılan Değer' ,
   'COLUMN_TITLE_DEFAULT_EMAIL' => 'Varsayılan Değer' ,
   'COLUMN_TITLE_EXT1' => 'Ekstra Meta Alanı 1' ,
   'COLUMN_TITLE_EXT2' => 'Ekstra Meta Alanı 2' ,
   'COLUMN_TITLE_EXT3' => 'Ekstra Meta Alanı 3' ,
   'COLUMN_TITLE_FRAME_HEIGHT' => 'IFrame Yüksekliği' ,
   'COLUMN_TITLE_HTML_CONTENT' => 'HTML' ,
   'COLUMN_TITLE_URL' => 'Varsayılan URL' ,
   'COLUMN_TITLE_AUDIT' => 'Değişiklik Tarihçesi' ,
   'COLUMN_TITLE_FTS' => 'Tam-Metin Arama Yapılabilir' ,
   'COLUMN_TITLE_REPORTABLE' => 'Raporlanabilir' ,
   'COLUMN_TITLE_MIN_VALUE' => 'Min. Değer' ,
   'COLUMN_TITLE_MAX_VALUE' => 'Mak. Değer' ,
   'COLUMN_TITLE_LABEL_ROWS' => 'Satırlar' ,
   'COLUMN_TITLE_LABEL_COLS' => 'Kolonlar' ,
   'COLUMN_TITLE_DISPLAYED_ITEM_COUNT' => '# Öğe görüntülendi' ,
   'COLUMN_TITLE_AUTOINC_NEXT' => 'Oto Arttırma Sonraki Değer' ,
   'COLUMN_DISABLE_NUMBER_FORMAT' => 'Biçimi Etkisizleştir' ,
   'COLUMN_TITLE_ENABLE_RANGE_SEARCH' => 'Aralık Aramayı etkinleştir' ,
   'COLUMN_TITLE_GLOBAL_SEARCH' => 'Global Arama' ,
   'LBL_DROP_DOWN_LIST' => 'Açılır Liste Öğeleri' ,
   'LBL_RADIO_FIELDS' => 'Radyo Alanları' ,
   'LBL_MULTI_SELECT_LIST' => 'Çoklu Seçim Listesi' ,
   'COLUMN_TITLE_PRECISION' => 'Doğruluk' ,
   'MSG_DELETE_CONFIRM' => 'Bu öğeyi silmek istediğinizden emin misiniz?' ,
   'POPUP_INSERT_HEADER_TITLE' => 'Özel Alan Ekle' ,
   'POPUP_EDIT_HEADER_TITLE' => 'Özel Alanı Değiştir' ,
   'LNK_SELECT_CUSTOM_FIELD' => 'Özel Alan Seçin' ,
   'LNK_REPAIR_CUSTOM_FIELD' => 'Özel Alanları Onar' ,
   'LBL_MODULE' => 'Modül' ,
   'COLUMN_TITLE_MASS_UPDATE' => 'Miktar Güncelleme' ,
   'COLUMN_TITLE_IMPORTABLE' => 'Veri Yüklenebilir' ,
   'COLUMN_TITLE_DUPLICATE_MERGE' => 'Aynı Kayıtları Birleştir' ,
   'LBL_LABEL' => 'Etiket' ,
   'LBL_DATA_TYPE' => 'Veri Tipi' ,
   'LBL_DEFAULT_VALUE' => 'Varsayılan Değer' ,
   'LBL_AUDITED' => 'Denetlenmiş' ,
   'LBL_REPORTABLE' => 'Raporlanabilir' ,
   'ERR_RESERVED_FIELD_NAME' => 'Saklanmış Anahtar Kelime' ,
   'ERR_SELECT_FIELD_TYPE' => 'Lütfen Alan Tipi Seçin' ,
   'ERR_FIELD_NAME_ALREADY_EXISTS' => 'Alan İsmi zaten var' ,
   'LBL_BTN_ADD' => 'Ekle' ,
   'LBL_BTN_EDIT' => 'Değiştir' ,
   'LBL_GENERATE_URL' => 'URL oluştur' ,
   'LBL_DEPENDENT_CHECKBOX' => 'Bağımlı' ,
   'LBL_DEPENDENT_TRIGGER' => 'Tetikleyici' ,
   'LBL_CALCULATED' => 'Hesaplanan Değer' ,
   'LBL_FORMULA' => 'Formül' ,
   'LBL_DYNAMIC_VALUES_CHECKBOX' => 'Bağımlı' ,
   'LBL_BTN_EDIT_VISIBILITY' => 'Görünürlüğü Değiştir' ,
   'LBL_LINK_TARGET' => 'Linkin açıldığı yer' ,
   'LBL_IMAGE_WIDTH' => 'Genişlik' ,
   'LBL_IMAGE_HEIGHT' => 'Yükseklik' ,
   'LBL_IMAGE_BORDER' => 'Sınır' ,
   'COLUMN_TITLE_VALIDATE_US_FORMAT' => 'U.S. Formatı' ,
   'LBL_DEPENDENT' => 'Bağımlı' ,
   'LBL_VISIBLE_IF' => 'Görünme Kriteri' ,
   'LBL_ENFORCED' => 'Zorunlu' ,
   'LBL_HELP' => 'Yardım' ,
   'LBL_HAS_PARENT' => 'Üst Kaydı var' ,
   'LBL_PARENT_DROPDOWN' => 'Üst Açılır-Liste' ,
   'LBL_EDIT_VIS' => 'Görünürlüğü Değiştir' );

?>
