<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/CampaignTrackers/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ID' => 'Id' ,
   'LBL_TRACKER_KEY' => 'Takip Edici Anahtarı' ,
   'LBL_TRACKER_URL' => 'Takip Edici URL' ,
   'LBL_TRACKER_NAME' => 'Takip Edici İsmi' ,
   'LBL_CAMPAIGN_ID' => 'Kampanya ID' ,
   'LBL_DATE_ENTERED' => 'Giriş Tarihi' ,
   'LBL_DATE_MODIFIED' => 'Değiştirilme Tarihi' ,
   'LBL_MODIFIED_USER_ID' => 'Değiştiren Kullanıcı ID' ,
   'LBL_CREATED_BY' => 'Oluşturan' ,
   'LBL_DELETED' => 'Silindi' ,
   'LBL_CAMPAIGN' => 'Kampanya' ,
   'LBL_OPTOUT' => 'Listeden Çıkış' ,
   'LBL_MODULE_NAME' => 'Kampanya Takip Edicileri' ,
   'LBL_EDIT_CAMPAIGN_NAME' => 'Kampanya İsmi:' ,
   'LBL_EDIT_TRACKER_NAME' => 'Takip Edici İsmi:' ,
   'LBL_EDIT_TRACKER_URL' => 'Takip Edici URL:' ,
   'LBL_SUBPANEL_TRACKER_NAME' => 'İsim' ,
   'LBL_SUBPANEL_TRACKER_URL' => 'URL' ,
   'LBL_SUBPANEL_TRACKER_KEY' => 'Anahtar' ,
   'LBL_EDIT_MESSAGE_URL' => 'Kampanya mesajı için URL:' ,
   'LBL_EDIT_TRACKER_KEY' => 'Takip Edici Anahtarı:' ,
   'LBL_EDIT_OPT_OUT' => 'Listeden Çıkış Linki?' ,
   'LNK_CAMPAIGN_LIST' => 'Kampanyalar' ,
   'LBL_EDIT_LAYOUT' => 'Yerleşimi Değiştir' );

?>
