<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Tasks/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Görevler' ,
   'LBL_TASK' => 'Görevler:' ,
   'LBL_MODULE_TITLE' => ' Görevler: Ana Sayfa' ,
   'LBL_SEARCH_FORM_TITLE' => ' Görev Arama' ,
   'LBL_LIST_FORM_TITLE' => ' Görev Listesi' ,
   'LBL_NEW_FORM_TITLE' => ' Görev Oluştur' ,
   'LBL_NEW_FORM_SUBJECT' => 'Not Konusu:' ,
   'LBL_NEW_FORM_DUE_DATE' => 'Son Bitirme Tarihi:' ,
   'LBL_NEW_FORM_DUE_TIME' => 'Son Bitirme Saati:' ,
   'LBL_NEW_TIME_FORMAT' => '(24:00)' ,
   'LBL_LIST_CLOSE' => 'Kapat' ,
   'LBL_LIST_SUBJECT' => 'Konu' ,
   'LBL_LIST_CONTACT' => 'Kontak' ,
   'LBL_LIST_PRIORITY' => 'Öncelik' ,
   'LBL_LIST_RELATED_TO' => 'İlişkili' ,
   'LBL_LIST_DUE_DATE' => 'Son Bitirme Tarihi' ,
   'LBL_LIST_DUE_TIME' => 'Son Bitirme Saati' ,
   'LBL_SUBJECT' => 'Not Konusu:' ,
   'LBL_STATUS' => 'Durum:' ,
   'LBL_DUE_DATE' => 'Son Bitirme Tarihi:' ,
   'LBL_DUE_TIME' => 'Son Bitirme Saati:' ,
   'LBL_PRIORITY' => 'Öncelik:' ,
   'LBL_COLON' => ':' ,
   'LBL_DUE_DATE_AND_TIME' => 'Son Bitirme Tarihi & Saati:' ,
   'LBL_START_DATE_AND_TIME' => 'Başlangıç Tarih & Saati:' ,
   'LBL_START_DATE' => 'Başlangıç Tarihi:' ,
   'LBL_LIST_START_DATE' => 'Başlangıç Tarihi' ,
   'LBL_START_TIME' => 'Başlangıç Saati:' ,
   'LBL_LIST_START_TIME' => 'Başlangıç Saati' ,
   'DATE_FORMAT' => '(yıl-ay-gün)' ,
   'LBL_NONE' => 'Yok' ,
   'LBL_CONTACT' => 'Kontak:' ,
   'LBL_EMAIL_ADDRESS' => 'E-Posta Adresi:' ,
   'LBL_PHONE' => 'Telefon:' ,
   'LBL_EMAIL' => 'E-Posta Adresi:' ,
   'LBL_DESCRIPTION_INFORMATION' => 'Tanım Bilgisi' ,
   'LBL_DESCRIPTION' => 'Tanım:' ,
   'LBL_NAME' => 'İsim:' ,
   'LBL_CONTACT_NAME' => 'Kontak İsmi' ,
   'LBL_LIST_COMPLETE' => 'Tamamlandı:' ,
   'LBL_LIST_STATUS' => 'Durum' ,
   'LBL_DATE_DUE_FLAG' => 'Bitirme Tarihi Yok' ,
   'LBL_DATE_START_FLAG' => 'Başlangıç Tarihi Yok' ,
   'ERR_DELETE_RECORD' => 'Kontak bilgisini silmek için bir kayıt no&#39;su belirtmelisiniz.' ,
   'ERR_INVALID_HOUR' => 'Lütfen 0-24 arası bir saat girin' ,
   'LBL_DEFAULT_PRIORITY' => 'Orta' ,
   'LBL_LIST_MY_TASKS' => 'Açık Görevlerim' ,
   'LNK_NEW_TASK' => 'Görev Oluştur' ,
   'LNK_TASK_LIST' => 'Görevleri Görüntüle' ,
   'LNK_IMPORT_TASKS' => 'Görev Verilerini Yükle' ,
   'LBL_CONTACT_FIRST_NAME' => 'Kontak İsmi' ,
   'LBL_CONTACT_LAST_NAME' => 'Kontak Soyismi' ,
   'LBL_LIST_ASSIGNED_TO_NAME' => 'Atanan Kullanıcı' ,
   'LBL_ASSIGNED_TO_NAME' => 'Atanan Kişi:' ,
   'LBL_LIST_DATE_MODIFIED' => 'Değiştirilme Tarihi' ,
   'LBL_CONTACT_ID' => 'Kontak ID:' ,
   'LBL_PARENT_ID' => 'Üst Kayıt ID:' ,
   'LBL_CONTACT_PHONE' => 'Kontak Telefonu:' ,
   'LBL_PARENT_NAME' => 'Üst Tipi:' ,
   'LBL_ACTIVITIES_REPORTS' => 'Aktiviteler Raporu' ,
   'LBL_TASK_INFORMATION' => 'Genel Bakış' ,
   'LBL_EDITLAYOUT' => 'Yerleşimi Değiştir' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => 'Notlar' ,
   'LBL_DATE_DUE' => 'Son Bitirme Tarihi' ,
   'LBL_EXPORT_ASSIGNED_USER_NAME' => 'Atanmış Kullanıcı İsmi' ,
   'LBL_EXPORT_ASSIGNED_USER_ID' => 'Atanmış Kullanıcı ID&#39;si' ,
   'LBL_EXPORT_MODIFIED_USER_ID' => 'Değiştiren ID' ,
   'LBL_EXPORT_CREATED_BY' => 'Oluşturan ID' ,
   'LBL_EXPORT_PARENT_TYPE' => 'İlişkili Olduğu Modül' ,
   'LBL_EXPORT_PARENT_ID' => 'İlişkili Olduğu ID' );

?>
