<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$dictionary['ATC_Appointments'] = array(
  'table' => 'atc_appointments',
  'audited' => true,
  'duplicate_merge' => true,
  'fields' => array(
    'appointment_number' =>
        array(
          'required' => false,
          'name' => 'appointment_number',
          'vname' => 'LBL_APPOINTMENT_NUMBER',
          'type' => 'int',
          'massupdate' => 0,
          'no_default' => true,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'calculated' => false,
          'size' => '20',
          'enable_range_search' => false,
          'disable_num_format' => '',
          'min' => false,
          'max' => false,
          'auto_increment' => true,
        ),
    'appointment_date_original' =>
        array(
          'required' => false,
          'name' => 'appointment_date_original',
          'vname' => 'LBL_APPOINTMENT_DATE_ORIGINAL',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'calculated' => false,
          'len' => '255',
          'size' => '20',
        ),
    'appointment_date' =>
        array(
          'required' => false,
          'name' => 'appointment_date',
          'vname' => 'LBL_APPOINTMENT_DATE',
          'type' => 'datetimecombo',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'calculated' => false,
          'size' => '20',
          'enable_range_search' => false,
          'dbType' => 'datetime',
        ),
    'appointment_status' =>
        array(
          'required' => true,
          'name' => 'appointment_status',
          'vname' => 'LBL_APPOINTMENT_STATUS',
          'type' => 'enum',
          'massupdate' => '1',
          'default' => '',
          'required' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => true,
          'reportable' => true,
          'len' => 100,
          'size' => '20',
          'options' => 'appointment_status',
          'studio' => 'visible',
          'dependency' => false,
        ),
    'opportunity_amount' =>
        array(
          'required' => true,
          'name' => 'opportunity_amount',
          'vname' => 'LBL_OPPORTUNITY_AMOUNT',
          'type' => 'enum',
          'massupdate' => '1',
          'default' => '',
          'required' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => true,
          'reportable' => true,
          'len' => 100,
          'size' => '20',
          'options' => 'appointment_amount_list',
          'studio' => 'visible',
          'dependency' => false,
        ),
    'appointment_place' =>
        array(
          'name' => 'appointment_place',
          'vname' => 'LBL_APPOINTMENT_PLACE',
          'type' => 'enum',
          'massupdate' => '1',
          'default' => '',
          'required' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => true,
          'reportable' => true,
          'len' => 100,
          'size' => '20',
          'options' => 'appointment_place',
          'studio' => 'visible',
          'dependency' => false,
        ),
    'appointment_duration_hours' =>
        array(
          'name' => 'appointment_duration_hours',
          'vname' => 'LBL_APPOINTMENT_DURATION_HOURS',
          'type' => 'enum',
          'massupdate' => '1',
          'default' => '',
          'required' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => true,
          'reportable' => true,
          'len' => 100,
          'size' => '20',
          'options' => 'appointment_duration_hours',
          'studio' => 'visible',
          'dependency' => false,
        ),
    'appointment_duration_minutes' =>
        array(
          'name' => 'appointment_duration_minutes',
          'vname' => 'LBL_APPOINTMENT_DURATION_MINUTES',
          'type' => 'enum',
          'massupdate' => '1',
          'default' => '',
          'required' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => true,
          'reportable' => true,
          'len' => 100,
          'size' => '20',
          'options' => 'duration_intervals',
          'studio' => 'visible',
          'dependency' => false,
        ),
    'sales_rep_feedback' =>
        array(
          'required' => true,
          'name' => 'sales_rep_feedback',
          'vname' => 'LBL_SALES_REP_FEEDBACK',
          'type' => 'text',
          'massupdate' => 0,
          'default' => '',
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => true,
          'reportable' => true,
          'size' => '20',
          'studio' => 'visible',
          'rows' => '6',
          'cols' => '60',
        ),
    'direct_phone' =>
        array(
          'name' => 'direct_phone',
          'vname' => 'LBL_DIRECT_PHONE',
          'type' => 'phone',
          'dbType' => 'varchar',
          'len' => 100,
          'unified_search' => true,
          'full_text_search' => array('boost' => 1),
          'comment' => 'Other phone number for the contact',
          'merge_filter' => 'enabled',
        ),
    'contact_email' =>
        array(
          'required' => false,
          'name' => 'contact_email',
          'vname' => 'LBL_CONTACT_EMAIL',
          'type' => 'varchar',
          'massupdate' => 0,
          'default' => '',
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => true,
          'reportable' => true,
          'len' => '255',
          'size' => '20',
        ),
  ),
  'relationships' => array(),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => array(
    array('name' => 'appointment_number', 'type' => 'unique', 'fields' => array('appointment_number'))
  )
);
if (!class_exists('VardefManager')) {
  require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('ATC_Appointments', 'ATC_Appointments', array('basic', 'team_security', 'assignable'));