<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ACLActions/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ACCESS_ALL' => 'Tümü' ,
   'LBL_ACCESS_NONE' => 'Yok' ,
   'LBL_ACCESS_OWNER' => 'Sahibi' ,
   'LBL_ACCESS_NORMAL' => 'Normal' ,
   'LBL_ACCESS_ADMIN' => 'Sistem Yöneticisi' ,
   'LBL_ACCESS_ENABLED' => 'Etkin' ,
   'LBL_ACCESS_DISABLED' => 'Etkisiz' ,
   'LBL_ACCESS_DEV' => 'Uygulama Geliştirici' ,
   'LBL_ACCESS_ADMIN_DEV' => 'Sistem Yöneticisi & Uygulama Geliştirici' ,
   'LBL_NAME' => 'İsim' ,
   'LBL_DESCRIPTION' => 'Tanım' ,
   'LIST_ROLES' => 'Roller Listesi' ,
   'LBL_USERS_SUBPANEL_TITLE' => 'Kullanıcılar' ,
   'LIST_ROLES_BY_USER' => 'Rolleri Kullanıcılara Göre Listele' ,
   'LBL_ROLES_SUBPANEL_TITLE' => 'Kullanıcı Rolleri' ,
   'LBL_SEARCH_FORM_TITLE' => 'Ara' ,
   'LBL_ACTION_VIEW' => 'Göster' ,
   'LBL_ACTION_EDIT' => 'Değiştir' ,
   'LBL_ACTION_DELETE' => 'Sil' ,
   'LBL_ACTION_IMPORT' => 'Veri Yükle' ,
   'LBL_ACTION_EXPORT' => 'Dışarı Aktar' ,
   'LBL_ACTION_LIST' => 'Liste' ,
   'LBL_ACTION_MASSUPDATE' => 'Miktar Güncelleme' ,
   'LBL_ACTION_ACCESS' => 'Erişim' ,
   'LBL_ACTION_ADMIN' => 'Kullanıcı Tipi' ,
   'LBL_ACCESS_DEFAULT' => 'Belirtilmedi' );

?>
