<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/SchedulersJobs/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_NAME' => 'Görev İsmi' ,
   'LBL_EXECUTE_TIME' => 'Çalıştırılma Zamanı' ,
   'LBL_SCHEDULER_ID' => 'Planlayıcı' ,
   'LBL_STATUS' => 'İş Durumu' ,
   'LBL_RESOLUTION' => 'Sonuç' ,
   'LBL_MESSAGE' => 'Mesajlar' ,
   'LBL_DATA' => 'İş Verisi' ,
   'LBL_REQUEUE' => 'Hata durumunda tekrar dene' ,
   'LBL_RETRY_COUNT' => 'Maksimum deneme sayısı' ,
   'LBL_FAIL_COUNT' => 'Başarısızlıklar ' ,
   'LBL_INTERVAL' => 'Denemeler arasındaki minimum aralık' ,
   'LBL_CLIENT' => 'Sahip olan istemci' ,
   'LBL_PERCENT' => 'Tamamlanma Yüzdesi' ,
   'ERR_CALL' => 'Fonksiyonu çağrılamıyor: %s' ,
   'ERR_CURL' => 'CURL Yok - URL işlerini çalıştıramazsınız' ,
   'ERR_FAILED' => 'Beklenmedik bir hata oluştu, PHP log&#39;larını ve sugarcrm.log kontrol ediniz' ,
   'ERR_PHP' => '%s [%d]: %s  içinde  %s  satırında %d' ,
   'ERR_NOUSER' => 'İş için belirtilen Kullanıcı ID&#39;si yok' ,
   'ERR_NOSUCHUSER' => 'Kullanıcı ID %s bulunamadı' ,
   'ERR_JOBTYPE' => 'Bilinmeyen iş türü: %s' ,
   'ERR_TIMEOUT' => 'Zaman aşımından dolayı hata oluştu' ,
   'ERR_JOB_FAILED_VERBOSE' => 'İş %1$s (%2$s) CRON çalıştırılmasında başarısız' );

?>
