<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN esb_QB_Transactions
 */


class esb_QB_Transactions_sugar extends Basic {
    public $new_schema = true;
    public $module_dir = 'esb_QB_Transactions';
    public $object_name = 'esb_QB_Transactions';
    public $table_name = 'esb_qb_transactions';
    public $importable = false;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $team_id;
    public $team_set_id;
    public $team_count;
    public $team_name;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $txn_num;
    public $txn_date;
    public $txn_status;
    public $txn_type;
    public $txn_class;
    public $txn_sales_tax;
    public $txn_po;
    public $txn_subtotal;
    public $currency_id;
    public $txn_tax_amount;
    public $txn_grand_total;
    public $txn_ar_account;
    public $txn_sales_terms;
    public $txn_due_date;
    public $txn_amount_outstanding;
    
    /**
     * This is a deprecated method, please start using __construct() as this
     * method will be removed in a future version.
     *
     * @see __construct
     * @deprecated
     */
    public function esb_QB_Transactions_sugar(){
        $GLOBALS['log']->deprecated('Calls to esb_QB_Transactions::esb_QB_Transactions are deprecated.');
        self::__construct();
    }

    public function __construct(){
        parent::__construct();
    }
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}