<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ProductTypes/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Ürün Tipleri' ,
   'LBL_MODULE_TITLE' => 'Ürün Tipleri: Ana Sayfa' ,
   'LBL_SEARCH_FORM_TITLE' => 'Ürün Tipi Arama' ,
   'LBL_LIST_FORM_TITLE' => 'Ürün Çeşit Listesi' ,
   'LBL_PRODUCTTYPE' => 'Ürün Tipi:' ,
   'LBL_LIST_NAME' => 'Ürün Tipi' ,
   'LBL_LIST_DESCRIPTION' => 'Tanım' ,
   'LBL_NAME' => 'Ürün Tipi:' ,
   'LBL_DESCRIPTION' => 'Tanım:' ,
   'LBL_LIST_LIST_ORDER' => 'Sıra' ,
   'LBL_LIST_ORDER' => 'Sıra:' ,
   'LNK_PRODUCT_LIST' => 'Ürün Kataloğunu Göster' ,
   'LNK_NEW_PRODUCT' => 'Katalog için Ürün Oluştur' ,
   'LNK_NEW_MANUFACTURER' => 'Üreticiler' ,
   'LNK_NEW_SHIPPER' => 'Nakliyat Sağlayıcıları' ,
   'LNK_NEW_PRODUCT_CATEGORY' => 'Ürün Kategorileri' ,
   'LNK_NEW_PRODUCT_TYPE' => 'Ürün Çeşit Listesi' ,
   'NTC_DELETE_CONFIRMATION' => 'Bu kaydı silmek istediğinizden emin misiniz?' ,
   'ERR_DELETE_RECORD' => 'Ürün tipini silmek için kayıt numarasını belirtmeniz gerekmektedir.' ,
   'NTC_LIST_ORDER' => 'Bu ürün tipinin, Ürün Tipi açılır-listesinde görünmesini istediğiniz sırayı belirleyin' ,
   'LNK_IMPORT_PRODUCT_TYPES' => 'Ürün Tipi Verilerini Yükle' ,
   'LBL_CREATED_BY' => 'Oluşturan' ,
   'LBL_EDITLAYOUT' => '' ,
   'LBL_EXPORT_MODIFIED_USER_ID' => 'Atanan Id' ,
   'LBL_EXPORT_CREATED_BY' => 'Oluşturan ID' );

?>
