<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Manufacturers/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ID' => 'ID' ,
   'LBL_CREATED_ID' => 'Oluşturan ID' ,
   'LBL_MODIFIED_ID' => 'Değiştiren ID' ,
   'LBL_MODULE_NAME' => 'Üreticiler' ,
   'LBL_MODULE_TITLE' => 'Üreticiler: Ana Sayfa' ,
   'LBL_SEARCH_FORM_TITLE' => 'Üretici Arama' ,
   'LBL_LIST_FORM_TITLE' => 'Üretici Listesi' ,
   'LBL_NEW_FORM_TITLE' => 'Yeni Üretici' ,
   'LBL_MANUFACTURER' => 'Üretici:' ,
   'LBL_LIST_NAME' => 'Üretici' ,
   'LBL_NAME' => 'Üretici:' ,
   'LBL_MODIFIED_BY' => 'Değiştiren' ,
   'LBL_CREATED_BY' => 'Oluşturan' ,
   'LBL_LIST_LIST_ORDER' => 'Sıra' ,
   'LBL_LIST_ORDER' => 'Sıra:' ,
   'LBL_LIST_STATUS' => 'Durum' ,
   'LBL_STATUS' => 'Durum:' ,
   'LNK_PRODUCT_LIST' => 'Ürün Kataloğunu Göster' ,
   'LNK_NEW_PRODUCT' => 'Katalog için Ürün Oluştur' ,
   'LNK_NEW_MANUFACTURER' => 'Üreticiler' ,
   'LNK_NEW_SHIPPER' => 'Nakliyat Sağlayıcıları' ,
   'LNK_NEW_PRODUCT_CATEGORY' => 'Ürün Kategorileri' ,
   'LNK_NEW_PRODUCT_TYPE' => 'Ürün Tipleri' ,
   'NTC_DELETE_CONFIRMATION' => 'Bu kaydı silmek istediğinizden emin misiniz?' ,
   'ERR_DELETE_RECORD' => 'Üreticiyi silmek için kayıt numarası belirtmeniz gerekmektedir.' ,
   'NTC_STATUS' => 'Bu üreticinin durumunu, İnaktif olarak belirleyerek Üretici açılır-listesinden kaldırın' ,
   'NTC_LIST_ORDER' => 'Bu üreticinin, Üretici açılır-listesinde görünmesini istediğiniz sırayı belirleyin' ,
   'LNK_IMPORT_MANUFACTURERS' => 'Üretici Verilerini Yükle' ,
   'LBL_EDITLAYOUT' => 'Yerleşimi Değiştir' ,
   'manufacturer_status_dom' => array (
      'Active' => 'Aktif' ,
      'Inactive' => 'İnaktif'   ));

?>
