<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Expressions/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'İfadeler' ,
   'LBL_MODULE_TITLE' => 'İş Akış Tetikleyicisi: Ana sayfa' ,
   'LBL_SEARCH_FORM_TITLE' => 'İş Akış Tetikleyicisi Araştırma' ,
   'LBL_LIST_FORM_TITLE' => 'Aksiyon Listesi' ,
   'LBL_NEW_FORM_TITLE' => 'Tetikleyici Oluştur' ,
   'LBL_LIST_NAME' => 'Tetikleyici İsmi:' ,
   'LBL_LIST_TYPE' => 'Tipi:' ,
   'LBL_LIST_EVAL' => 'Deneme:' ,
   'LBL_LIST_FIELD' => 'Alan:' ,
   'LBL_NAME' => 'Tetikleyici İsmi:' ,
   'LBL_FIELD' => 'Alan:' ,
   'LBL_TYPE' => 'Tipi:' ,
   'LBL_EVAL' => 'Tetikleyici Değerlendirmesi:' ,
   'LBL_SHOW_PAST' => 'Eski Değeri Değiştir:' ,
   'LNK_NEW_TRIGGER' => 'Tetikleyici Oluştur' ,
   'LNK_TRIGGER' => 'İş Akışı Tetikleyicileri' ,
   'LBL_TIME_PAST' => 'önce' ,
   'LBL_TIME_FUTURE' => 'şuandan itibaren' ,
   'LBL_ACTION_UPDATE' => 'Güncellenen alanlar başlatıldı' ,
   'LBL_ACTION_UPDATE_REL' => 'İlişkili Güncellenen alanlar' ,
   'LBL_ACTION_NEW' => 'Yeni Oluştur' ,
   'LBL_RECORD' => 'Kayıt' ,
   'LBL_NEXT_BUTTON' => 'Sonraki' ,
   'LBL_PREVIOUS_BUTTON' => 'Önceki' ,
   'LBL_LIST_ACTION_DESCRIPTION' => 'Gerçekleştirilecek Aksiyonlar:' ,
   'LBL_PLEASE_SELECT' => 'Lütfen Seçiniz' ,
   'LBL_TIME_INT' => 'en azından' ,
   'LBL_REL1' => 'İlişkili Modül:' ,
   'LBL_REL2' => 'İlişkili Modülün modülü:' ,
   'LBL_PLEASE_SEL_TARGET' => 'Lütfen bir hedef modülü seçin' ,
   'LBL_ASSOCIATED_WITH' => ' ilgili ile ilişkili' );

?>
