<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/EAPM/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ASSIGNED_TO_ID' => 'Atanan Kullanıcı ID' ,
   'LBL_ASSIGNED_TO_NAME' => 'Sugar Kullanıcısı' ,
   'LBL_ID' => 'ID' ,
   'LBL_DATE_ENTERED' => 'Oluşturulma Tarihi' ,
   'LBL_DATE_MODIFIED' => 'Değiştirilme Tarihi' ,
   'LBL_MODIFIED' => 'Değiştiren' ,
   'LBL_MODIFIED_ID' => 'Değiştiren ID' ,
   'LBL_MODIFIED_NAME' => 'Değiştiren Kişinin İsmi' ,
   'LBL_CREATED' => 'Oluşturan' ,
   'LBL_CREATED_ID' => 'Oluşturan ID' ,
   'LBL_DESCRIPTION' => 'Tanım' ,
   'LBL_DELETED' => 'Silindi' ,
   'LBL_NAME' => 'Uygulama Kullanıcı İsmi' ,
   'LBL_CREATED_USER' => 'Oluşturan Kullanıcı' ,
   'LBL_MODIFIED_USER' => 'Değiştiren Kullanıcı' ,
   'LBL_LIST_NAME' => 'İsim' ,
   'LBL_TEAM' => 'Takımlar' ,
   'LBL_TEAMS' => 'Takımlar' ,
   'LBL_TEAM_ID' => 'Takım ID' ,
   'LBL_LIST_FORM_TITLE' => 'Harici Hesapların Listesi' ,
   'LBL_MODULE_NAME' => 'Harici Hesap' ,
   'LBL_MODULE_TITLE' => 'Harici Hesaplar' ,
   'LBL_HOMEPAGE_TITLE' => 'Harici Hesaplarım' ,
   'LNK_NEW_RECORD' => 'Harici Hesap Oluştur' ,
   'LNK_LIST' => 'Harici Hesapları Görüntüle' ,
   'LNK_IMPORT_SUGAR_EAPM' => 'Harici Hesap Verilerini Yükle' ,
   'LBL_SEARCH_FORM_TITLE' => 'Harici Kaynak Ara' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => 'Tarihçeyi Gör' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Aktiviteler' ,
   'LBL_SUGAR_EAPM_SUBPANEL_TITLE' => 'Harici Hesaplar' ,
   'LBL_NEW_FORM_TITLE' => 'Yeni Harici Hesap' ,
   'LBL_PASSWORD' => 'Uygulama Şifresi' ,
   'LBL_USER_NAME' => 'Uygulama Kullanıcı İsmi' ,
   'LBL_URL' => 'URL' ,
   'LBL_APPLICATION' => 'Uygulama' ,
   'LBL_API_DATA' => 'API Verisi' ,
   'LBL_API_TYPE' => 'Giriş Türü' ,
   'LBL_API_CONSKEY' => 'Müşteri Anahtarı' ,
   'LBL_API_CONSSECRET' => 'Müşteri Şifresi' ,
   'LBL_API_OAUTHTOKEN' => 'OAuth Anahtarı' ,
   'LBL_AUTH_UNSUPPORTED' => 'Bu yetkilendirme yöntemi uygulama tarafından desteklenmiyor' ,
   'LBL_AUTH_ERROR' => 'Bu hesaba bağlanma girişiminiz başarısız oldu.' ,
   'LBL_VALIDATED' => 'Bağlı' ,
   'LBL_ACTIVE' => 'Aktif' ,
   'LBL_OAUTH_NAME' => '%s' ,
   'LBL_SUGAR_USER_NAME' => 'Sugar Kullanıcısı' ,
   'LBL_DISPLAY_PROPERTIES' => 'Görüntü Özellikleri' ,
   'LBL_CONNECT_BUTTON_TITLE' => 'Bağlan' ,
   'LBL_NOTE' => 'Lütfen Dikkate Alınız' ,
   'LBL_CONNECTED' => 'Bağlı' ,
   'LBL_DISCONNECTED' => 'Bağlı Değil' ,
   'LBL_ERR_NO_AUTHINFO' => 'Bu hesap için kimlik doğrulama bilgisi yok.' ,
   'LBL_ERR_NO_TOKEN' => 'Bu hesap için geçerli giriş anahtarları yoktur.' ,
   'LBL_ERR_FAILED_QUICKCHECK' => 'Şu anda {0} hesabınıza bağlı değilsiniz. Hesabınıza giriş yapmak ve bağlantıyı tekrar etkinleştirmek ve için Tamam tuşuna tıklayın.' ,
   'LBL_MEET_NOW_BUTTON' => 'Şimdi Görüş' ,
   'LBL_VIEW_LOTUS_LIVE_MEETINGS' => 'Yaklaşan LotusLive&trade; Toplantılarını Görüntüle' ,
   'LBL_TITLE_LOTUS_LIVE_MEETINGS' => 'Gelecek LotusLive&trade; Toplantıları' ,
   'LBL_VIEW_LOTUS_LIVE_DOCUMENTS' => 'LotusLive&trade; Dosyalarını Görüntüle' ,
   'LBL_TITLE_LOTUS_LIVE_DOCUMENTS' => 'LotusLive&trade; Dosyaları' ,
   'LBL_REAUTHENTICATE_LABEL' => 'Tekrar Kimlik Doğrulama' ,
   'LBL_REAUTHENTICATE_KEY' => 'a' ,
   'LBL_APPLICATION_FOUND_NOTICE' => 'Bu uygulama için bir hesap zaten var. Biz hesabınızı eski haline getirdik.' ,
   'LBL_OMIT_URL' => '(http:// veya https:// kısmını atla)' ,
   'LBL_OAUTH_SAVE_NOTICE' => '<b>Bağlan</b> tuşuna bastığınızda, hesap bilgilerinizi sağlayacağınız ve Sugar tarafından erişime izin vereceğiniz sayfaya yönlendirilirsiniz. Bağlandıktan sonra kullanıcı tekrar Sugar ekranlarına yönlendirilmektedir.' ,
   'LBL_BASIC_SAVE_NOTICE' => 'Sugar sistemine bağlanmak için <b>Bağlan</b> tuşuna tıklayın.' ,
   'LBL_ERR_FACEBOOK' => 'Facebook hata döndürdü ve besleme gösterilemiyor.' ,
   'LBL_ERR_NO_RESPONSE' => 'Bu hesaba bağlanmaya çalışırken bir hata oluştu.' ,
   'LBL_ERR_TWITTER' => 'Twitter hata döndürdü ve besleme gösterilemiyor.' ,
   'LBL_ERR_POPUPS_DISABLED' => 'Lütfen tarayıcı açılabilir pencerelerini aktifleştirin veya bağlanabilmek için istisnalar listesine "{0}" web sitesini ekleyin.' );

?>
