<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Holidays/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'Tatiller' ,
   'LBL_MODULE_TITLE' => 'Tatiller: Ana Sayfa' ,
   'LBL_HOLIDAY' => 'Tatil:' ,
   'LBL_HOLIDAY_DATE' => 'Tatil Tarihi:' ,
   'LBL_NAME' => 'Tatil Tarihi:' ,
   'LBL_DESCRIPTION' => 'Tanım:' ,
   'LBL_RESOURCE_NAME' => 'Kaynak İsmi' ,
   'LBL_SEARCH_FORM_TITLE' => 'Tatil Arama' ,
   'LBL_LIST_FORM_TITLE' => 'Tatil Listesi' ,
   'LNK_NEW_HOLIDAY' => 'Tatil Ekle' ,
   'LNK_HOLIDAYS' => 'Tatiller' ,
   'LBL_USERS_SUBPANEL_TITLE' => 'Kullanıcılar' ,
   'LBL_USER_HOLIDAY_SUBPANEL_TITLE' => 'Kullanıcı Tatilleri' ,
   'LBL_RESOURCE' => 'Kaynak:' ,
   'LBL_PERSON_TYPE' => 'Kişi tipi' ,
   'LBL_RELATED_MODULE' => 'İlişkili Modüller:' ,
   'LBL_SELECT_RESOURCE_TYPE' => 'Kaynak Tipini Seçin...' ,
   'LBL_USER' => 'Kullanıcı' ,
   'LBL_CONTACT' => 'Kontak' );

?>
