<?php $dictionary['RLS_LinkedinParserConfig'] = array( 'table' => 'rls_linkedinparserconfig', 'audited' => true,
 'duplicate_merge' => true, 'fields' => array( 'rls_skills' => array( 'required' => false, 'name' => 'rls_skills',
 'vname' => 'LBL_RLS_SKILLS', 'type' => 'bool', 'massupdate' => 0, 'default' => '0', 'no_default' => false,
 'comments' => '', 'help' => '', 'importable' => 'true', 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0',
 'audited' => false, 'reportable' => true, 'unified_search' => false, 'merge_filter' => 'disabled',
 'size' => '20', ), 'rls_working_experience' => array( 'required' => false, 'name' => 'rls_working_experience',
 'vname' => 'LBL_RLS_WORKING_EXPERIENCE', 'type' => 'bool', 'massupdate' => 0, 'default' => '0',
 'no_default' => false, 'comments' => '', 'help' => '', 'importable' => 'true', 'duplicate_merge' => 'disabled',
 'duplicate_merge_dom_value' => '0', 'audited' => false, 'reportable' => true, 'unified_search' => false,
 'merge_filter' => 'disabled', 'size' => '20', ), 'rls_parse_accounts' => array( 'required' => false,
 'name' => 'rls_parse_accounts', 'vname' => 'LBL_RLS_PARSE_ACCOUNTS', 'type' => 'bool', 'massupdate' => 0,
 'default' => '0', 'no_default' => false, 'comments' => '', 'help' => '', 'importable' => 'true',
 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0', 'audited' => false, 'reportable' => true,
 'unified_search' => false, 'merge_filter' => 'disabled', 'size' => '20', ), 'rls_job_list' => array(
 'required' => false, 'name' => 'rls_job_list', 'vname' => 'LBL_RLS_JOB_LIST', 'type' => 'bool',
 'massupdate' => 0, 'default' => '0', 'no_default' => false, 'comments' => '', 'help' => '', 'importable' => 'true',
 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0', 'audited' => false, 'reportable' => true,
 'unified_search' => false, 'merge_filter' => 'disabled', 'size' => '20', ), 'rls_target_list' => array(
 'required' => false, 'name' => 'rls_target_list', 'vname' => 'LBL_RLS_TARGET_LIST', 'type' => 'bool',
 'massupdate' => 0, 'default' => '0', 'no_default' => false, 'comments' => '', 'help' => '', 'importable' => 'true',
 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0', 'audited' => false, 'reportable' => true,
 'unified_search' => false, 'merge_filter' => 'disabled', 'size' => '20', ), 'rls_show_technical_data' => array(
 'required' => false, 'name' => 'rls_show_technical_data', 'vname' => 'LBL_RLS_SHOW_TECHNICAL_DATA',
 'type' => 'bool', 'massupdate' => 0, 'default' => '0', 'no_default' => false, 'comments' => '',
 'help' => '', 'importable' => 'true', 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0',
 'audited' => false, 'reportable' => true, 'unified_search' => false, 'merge_filter' => 'disabled',
 'size' => '20', ), 'rls_notes_name_mask' => array( 'required' => false, 'name' => 'rls_notes_name_mask',
 'vname' => 'LBL_RLS_NOTES_NAME_MASK', 'type' => 'varchar', 'massupdate' => 0, 'no_default' => false,
 'comments' => '', 'help' => '', 'importable' => 'true', 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0',
 'audited' => false, 'reportable' => true, 'unified_search' => false, 'merge_filter' => 'disabled',
 'size' => '20', ), 'rls_assign_to' => array( 'required' => false, 'name' => 'rls_assign_to', 'vname' => 'LBL_RLS_ASSIGN_TO',
 'type' => 'enum', 'massupdate' => 0, 'default' => 'current_user', 'no_default' => false, 'comments' => '',
 'help' => '', 'importable' => 'true', 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0',
 'audited' => false, 'reportable' => true, 'unified_search' => false, 'merge_filter' => 'disabled',
 'size' => '20', 'options' => 'rls_assign_to_list', 'studio' => 'visible', 'dependency' => false,
 ), 'rls_leads_status_f' => array( 'required' => false, 'name' => 'rls_leads_status_f', 'vname' => 'LBL_RLS_LEADS_STATUS_F',
 'type' => 'enum', 'massupdate' => 0, 'no_default' => false, 'comments' => '', 'help' => '', 'importable' => 'true',
 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0', 'audited' => false, 'reportable' => true,
 'unified_search' => false, 'merge_filter' => 'disabled', 'size' => '20', 'options' => 'lead_status_dom',
 'studio' => 'visible', 'dependency' => false, ), 'rls_candidate_status_f' => array( 'required' => false,
 'name' => 'rls_candidate_status_f', 'vname' => 'LBL_RLS_CANDIDATE_STATUS_F', 'type' => 'enum', 'massupdate' => 0,
 'no_default' => false, 'comments' => '', 'help' => '', 'importable' => 'true', 'duplicate_merge' => 'disabled',
 'duplicate_merge_dom_value' => '0', 'audited' => false, 'reportable' => true, 'unified_search' => false,
 'merge_filter' => 'disabled', 'size' => '20', 'options' => 'lead_status_dom', 'studio' => 'visible',
 'dependency' => false, ), 'list_order_modules_disabled_id' => array( 'name' => 'list_order_modules_disabled_id',
 'vname' => 'LBL_LIST_ORDER_MODULES_DISABLED_ID', 'function' => array( 'name' => 'getListOrderModulesDisabledHTML',
 'returns' => 'html', 'include' => 'modules/RLS_LinkedinParserConfig/rlsMultiselectWidget.php', ),
 'type' => 'varchar', 'massupdate' => 0, 'no_default' => false, 'comments' => '', 'help' => '',
 'importable' => 'true', 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0', 'audited' => false,
 'reportable' => true, 'unified_search' => false, 'merge_filter' => 'disabled', 'size' => '20', 'inline_edit' => false,
 ), 'accounts_duplicate' => array( 'name' => 'accounts_duplicate', 'vname' => 'LBL_LIST_ACCOUNTS_DUPLICATE',
 'function' => array( 'name' => 'getListDuplicateHTML', 'returns' => 'html', 'include' => 'modules/RLS_LinkedinParserConfig/rlsMultiselectWidget.php',
 ), 'type' => 'varchar', 'massupdate' => 0, 'no_default' => false, 'comments' => '', 'help' => '',
 'importable' => 'true', 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0', 'audited' => false,
 'reportable' => true, 'unified_search' => false, 'merge_filter' => 'disabled', 'size' => '20', 'inline_edit' => false,
 ), 'contacts_duplicate' => array( 'name' => 'contacts_duplicate', 'vname' => 'LBL_LIST_CONTACTS_DUPLICATE',
 'function' => array( 'name' => 'getListDuplicateHTML', 'returns' => 'html', 'include' => 'modules/RLS_LinkedinParserConfig/rlsMultiselectWidget.php',
 ), 'type' => 'varchar', 'massupdate' => 0, 'no_default' => false, 'comments' => '', 'help' => '',
 'importable' => 'true', 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0', 'audited' => false,
 'reportable' => true, 'unified_search' => false, 'merge_filter' => 'disabled', 'size' => '20', 'inline_edit' => false,
 ), 'leads_duplicate' => array( 'name' => 'leads_duplicate', 'vname' => 'LBL_LIST_LEADS_DUPLICATE',
 'function' => array( 'name' => 'getListDuplicateHTML', 'returns' => 'html', 'include' => 'modules/RLS_LinkedinParserConfig/rlsMultiselectWidget.php',
 ), 'type' => 'varchar', 'massupdate' => 0, 'no_default' => false, 'comments' => '', 'help' => '',
 'importable' => 'true', 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0', 'audited' => false,
 'reportable' => true, 'unified_search' => false, 'merge_filter' => 'disabled', 'size' => '20', 'inline_edit' => false,
 ), 'prospects_duplicate' => array( 'name' => 'prospects_duplicate', 'vname' => 'LBL_LIST_PROSPECTS_DUPLICATE',
 'function' => array( 'name' => 'getListDuplicateHTML', 'returns' => 'html', 'include' => 'modules/RLS_LinkedinParserConfig/rlsMultiselectWidget.php',
 ), 'type' => 'varchar', 'massupdate' => 0, 'no_default' => false, 'comments' => '', 'help' => '',
 'importable' => 'true', 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0', 'audited' => false,
 'reportable' => true, 'unified_search' => false, 'merge_filter' => 'disabled', 'size' => '20', 'inline_edit' => false,
 ), 'rls_candidates_duplicate' => array( 'name' => 'rls_candidates_duplicate', 'vname' => 'LBL_LIST_RLS_CANDIDATES_DUPLICATE',
 'function' => array( 'name' => 'getListDuplicateHTML', 'returns' => 'html', 'include' => 'modules/RLS_LinkedinParserConfig/rlsMultiselectWidget.php',
 ), 'type' => 'varchar', 'massupdate' => 0, 'no_default' => false, 'comments' => '', 'help' => '',
 'importable' => 'true', 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0', 'audited' => false,
 'reportable' => true, 'unified_search' => false, 'merge_filter' => 'disabled', 'size' => '20', 'inline_edit' => false,
 ), 'jobs_allow_statuses_list' => array( 'required' => false, 'name' => 'jobs_allow_statuses_list',
 'vname' => 'LBL_JOBS_ALLOW_STATUSES', 'type' => 'multienum', 'function' => array( 'name' => 'getJobStatusActualList',
 'returns' => 'options', 'include' => 'modules/RLS_LinkedinParserConfig/rlsMultiselectWidget.php',
 ), 'massupdate' => 1, 'comments' => '', 'help' => '', 'importable' => 'true', 'duplicate_merge' => 'disabled',
 'duplicate_merge_dom_value' => '0', 'audited' => false, 'reportable' => true, 'calculated' => false,
 'size' => '20', 'studio' => 'visible', 'dependency' => '', 'default' => '', ), 'ignore_target_list_security' => array(
 'required' => false, 'name' => 'ignore_target_list_security', 'vname' => 'LBL_TARGET_LIST_SECURITY',
 'type' => 'bool', 'massupdate' => 0, 'default' => '0', 'no_default' => false, 'comments' => '',
 'help' => '', 'importable' => 'true', 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0',
 'audited' => false, 'reportable' => true, 'unified_search' => false, 'merge_filter' => 'disabled',
 'size' => '20', ), 'ignore_job_list_security' => array( 'required' => false, 'name' => 'ignore_job_list_security',
 'vname' => 'LBL_JOB_LIST_SECURITY', 'type' => 'bool', 'massupdate' => 0, 'default' => '0', 'no_default' => false,
 'comments' => '', 'help' => '', 'importable' => 'true', 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0',
 'audited' => false, 'reportable' => true, 'unified_search' => false, 'merge_filter' => 'disabled',
 'size' => '20', ), 'ignore_dublicates_team_security' => array( 'required' => false, 'name' => 'ignore_dublicates_team_security',
 'vname' => 'LBL_RLS_DUPLICATE_TEAM_SECURITY', 'type' => 'bool', 'massupdate' => 0, 'default' => '0',
 'no_default' => false, 'comments' => '', 'help' => '', 'importable' => 'true', 'duplicate_merge' => 'disabled',
 'duplicate_merge_dom_value' => '0', 'audited' => false, 'reportable' => true, 'unified_search' => false,
 'merge_filter' => 'disabled', 'size' => '20', ), 'default_module_search' => array( 'name' => 'default_module_search',
 'vname' => 'LBL_DEFAULT_MODULE_SEARCH', 'function' => array( 'name' => 'getDefaultModuleSearchHTML',
 'returns' => 'html', 'include' => 'modules/RLS_LinkedinParserConfig/rlsMultiselectWidget.php', ),
 'type' => 'varchar', 'massupdate' => 0, 'no_default' => false, 'comments' => '', 'help' => '',
 'importable' => 'true', 'duplicate_merge' => 'disabled', 'duplicate_merge_dom_value' => '0', 'audited' => false,
 'reportable' => true, 'unified_search' => false, 'merge_filter' => 'disabled', 'size' => '20', 'inline_edit' => false,
 ), ), 'relationships' => array(), 'optimistic_locking' => true, 'unified_search' => true, ); if (!class_exists('VardefManager')) {
 require_once 'include/SugarObjects/VardefManager.php'; } VardefManager::createVardef('RLS_LinkedinParserConfig',
 'RLS_LinkedinParserConfig', array('basic', 'assignable')); 