<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Connectors/connectors/sources/ext/soap/hoovers/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$connector_strings = array ( 
   'LBL_LICENSING_INFO' => '<table border="0" cellspacing="1"><tr><td valign="top" width="35%" class="dataLabel"><image src="MANUAL CHANGE ADVOCOTEK" border="0"></td><td width="65%" valign="top" class="dataLabel">Hoovers©, şirketler hakkındaki güncel bilgileri SugarCRM ürünlerini kullanan kullanıcılarla ücretsiz sağlar. Daha fazla bilgi ve şirketler hakkındaki raporlar için <a href="http://www.hoovers.com" target="_blank">http://www.hoovers.com</a>.</td></tr></table>' ,
   'LBL_ID' => 'ID' ,
   'LBL_NAME' => 'Şirket İsmi' ,
   'LBL_DUNS' => 'DUNS' ,
   'LBL_PARENT_DUNS' => 'Ana DUNS' ,
   'LBL_STREET' => 'Sokak' ,
   'LBL_ADDRESS_STREET1' => '1.Adres' ,
   'LBL_ADDRESS_STREET2' => '2.Adres' ,
   'LBL_CITY' => 'Şehir' ,
   'LBL_STATE' => 'Eyalet' ,
   'LBL_COUNTRY' => 'Ülke' ,
   'LBL_ZIP' => 'Posta Kodu' ,
   'LBL_FINSALES' => 'Yıllık Satış Miktarı' ,
   'LBL_HQPHONE' => 'Ofis Telefonu' ,
   'LBL_TOTAL_EMPLOYEES' => 'Toplam Çalışan' ,
   'LBL_PRIMARY_URL' => 'Asıl URL' ,
   'LBL_DESCRIPTION' => 'Tanım' ,
   'LBL_SYNOPSIS' => 'Özet' ,
   'LBL_LOCATION_TYPE' => 'Konum Tipi' ,
   'LBL_COMPANY_TYPE' => 'Şirket Tipi' ,
   'ERROR_NULL_CLIENT' => 'Hoovers a bağlanmak için SoapClient oluşturulamadı. Servis kullanım dışı veya lisans anahtarınızın süresi doldu veya günlük kullanım limitine ulaştınız.' ,
   'ERROR_MISSING_SOAP_LIBRARIES' => 'Hata: SOAP kütüphaneleri yüklenemiyor (SoapClient, SoapHeader).' ,
   'hoovers_endpoint' => 'Bitiş Noktası URL' ,
   'hoovers_wsdl' => 'WSDL URL' ,
   'hoovers_api_key' => 'API Anahtar' );

?>
