<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ContractTypes/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ID' => 'Id' ,
   'LBL_DATE_ENTERED' => 'Giriş Tarihi' ,
   'LBL_DATE_MODIFIED' => 'Değiştirilme Tarihi' ,
   'LBL_MODIFIED_USER_ID' => 'Değiştiren Kullanıcı ID' ,
   'LBL_CREATED_BY' => 'Oluşturan' ,
   'LBL_DELETED' => 'Silindi' ,
   'LBL_DOCUMENTS' => 'Dokümanlar' ,
   'LBL_TYPE_NAME' => 'Tip İsmi' ,
   'LBL_MODULE_NAME' => 'Kontrat Tipi' ,
   'LBL_MODULE_TITLE' => 'Kontrat Tipleri' ,
   'LBL_LIST_FORM_TITLE' => 'Kontrat Tipleri' ,
   'LBL_CONTRACT_TYPE' => 'Kontrat Tipi' ,
   'LBL_LIST_ORDER' => 'Sıra:' ,
   'LNK_CONTRACTTYPE_LIST' => 'Kontrat Tiplerini Görüntüle' ,
   'LNK_NEW_CONTRACTTYPE' => 'Kontrat Tipi Oluştur' ,
   'LBL_LIST_NAME' => 'İsim' ,
   'LBL_LIST_LIST_ORDER' => 'Sıra' ,
   'LBL_NAME' => 'İsim:' ,
   'NTC_DELETE_CONFIRMATION' => 'Kontrat Tipini silmek istediğinizden emin misiniz?' ,
   'LBL_DOCUMENTS_SUBPANEL_TITLE' => 'Dokümanlar' ,
   'LBL_SEARCH_FORM_TITLE' => 'Kontrat Tipleri Araştırması' );

?>
